### ISSUE TITLE
Unexpected token in HQL Update @Query when base package name starts with an SQL Keyword [DATAJPA-659]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1037]
**[Chinmay Shah](https://jira.spring.io/secure/ViewProfile.jspa?name=chinmayshah24)** opened **[DATAJPA-659](https://jira.spring.io/browse/DATAJPA-659?redirect=false)** and commented

Here's my query which is failing validation -

```java
@Modifying
@Query("update ENTITYCLASSXXXXXXXXXXXXXXXXXXXXXXXX smpb set smpb.active = :active where smpb.sx1 = :sx1 and smpb.sx2 = :sx2")
void updateXXX(@Param("sx1") String sx1, @Param("sx2") Integer sx2, @Param("active") Boolean active);
```

Here's the reason:

```
16 Jan 2015 21:09:57,824 ERROR: org.hibernate.hql.internal.ast.ErrorCounter - line 1:8: unexpected token: in
16 Jan 2015 21:09:57,825 ERROR: org.hibernate.hql.internal.ast.ErrorCounter - line 1:8: unexpected token: in
line 1:8: unexpected token: in
	at org.hibernate.hql.internal.antlr.HqlBaseParser.updateStatement(HqlBaseParser.java:239)
	at org.hibernate.hql.internal.antlr.HqlBaseParser.statement(HqlBaseParser.java:169)
```

---

**Attachments:**
- [DummyInfo.java](https://jira.spring.io/secure/attachment/22602/DummyInfo.java) (_525 bytes_)
- [DummyInfoRepository.java](https://jira.spring.io/secure/attachment/22603/DummyInfoRepository.java) (_497 bytes_)
- [log.txt](https://jira.spring.io/secure/attachment/22601/log.txt) (_1.95 kB_)
- [set_log.txt](https://jira.spring.io/secure/attachment/22604/set_log.txt) (_18.05 kB_)

**Comment by schauder** [comment]
It seems you have three options:
1. Open a ticket with Hibernate, since for all what we can tell it is a problem with their parser
2. Rename your entity to avoid the issue
3. Convince us that it is a Spring Data JPA issue and not a Hibernate issue by providing a reproducer that demonstrates that the problem exists with Spring Data JPA, but not when executing the query with the `EntityManager` directly.
