### ISSUE TITLE
Support IgnoreCase for In Clause [DATAJPA-676]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1053]
**[Marek Kaluzny](https://jira.spring.io/secure/ViewProfile.jspa?name=mkaluzny)** opened **[DATAJPA-676](https://jira.spring.io/browse/DATAJPA-676?redirect=false)** and commented

Currently, IgnoreCase for In queries is ignored, for example:

```
findByFirstNameInIgnoreCase(Collection<String> names)
```

does standard query, without UPPER clause, and I think it should generate something like:

```
UPPER(entity0_.firstName) in ( UPPER(?), ... )
```

---

**Affects:** 1.7.2 (Evans SR2)

**Comment by gregturn** [comment]
It would frankly be easier to apply some transformation on the incoming `Collection<String> names` rather than trying to twist `JpaQueryCreator` to handle this. 

The JPA APIs don't lend themselves to doing this directly, so we'd need a transformation inside Spring Data JPA that is rather tricky, and I'm not sure worth the effort.

In lieu of bending JPA to do this for us, you can do this today:

```
Collection<String> names = List.of("Dave", "Julia");
return repo.findByFirstNameUpperIn(coll.stream().map(String::toUpperCase).toList());
```

This should apply an `UPPER` against the `FIRST_NAME` column. And by "uppering" the incoming data, you can make it all work. This may be adequate for now.

**Comment by gregturn** [comment]
Duplicates #1053.

**Comment by gregturn** [comment]
Also see https://github.com/spring-projects/spring-data-jpa/pull/261 and https://github.com/spring-projects/spring-data-jpa/commit/6401f91c83c8800d26750fb32948653d220500a0.
