### ISSUE TITLE
Unnecessary OUTER JOIN are generated for counting one single table [DATAJPA-729]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1102]
**[Guillaume Rosauro](https://jira.spring.io/secure/ViewProfile.jspa?name=willome)** opened **[DATAJPA-729](https://jira.spring.io/browse/DATAJPA-729?redirect=false)** and commented

Unnecessary outer joins are generated when a single table is queried for counting. It could be a duplicate of : https://jira.spring.io/browse/DATAJPA-401

```java
@Entity
public class BankAccountControl {
    @Id
    private long id;
 
    @ManyToOne
    @JoinColumn(name ="uac_id", nullable = false)
    private UserAccount userAccount;
 
    // setter/getters are here
}
 
@Entity
public class UserAccount {
 
    @Id
    @Column(name = "uac_id")
    private long id;
    private String firstname;
    private String lastname;
 
    // setter/getters are here
}
```

SQL generated with spring-data-jpa :

```java
public Long countByUserAccount_id(Long id);

select
        count(bankaccoun0_.COB_ID) as col_0_0_ 
    from
        USR_CONTROL_BANK_ACCOUNT bankaccoun0_ 
    left outer join
        USR_USER_ACCOUNT useraccoun1_ 
            on bankaccoun0_.UAC_ID=useraccoun1_.UAC_ID 
    where
        useraccoun1_.UAC_ID=?

```

SQL generated with jpql :

```java
@Query(value = "select count(bac) from BankAccountControl bac where bac.userAccount.id = ?1")
public Long countUserAccounts(Long id);

 select
        count(bankaccoun0_.COB_ID) as col_0_0_ 
    from
        USR_CONTROL_BANK_ACCOUNT bankaccoun0_ 
    where
        bankaccoun0_.UAC_ID=?

```

---

**Affects:** 1.7.2 (Evans SR2), 1.8 GA (Fowler)

**Comment by gregturn** [comment]
1. This isn't the same as #809, That issue involved joining with the same table twice to handle matching against two different columns. And they fixed that.
2. This issue is hinting that when you write a `countBy` operation and you explicitly go through a relationship, that Spring Data JPA should optimize the query and remove unnecessary joins. I'm not quite sure Spring Data JPA can do such an optimization. Of if its even necessary.

First of all, if you're concerned about it being a LEFT OUTER JOIN, that's merely a byproduct of `@ManyToOne` not having its `optional` parameter set to false. Because it COULD be `null`, we have to use a LEFT OUTER JOIN. If you can assert that in all situations, the field will be populated, you can adjust the entity's definition to say so.

Second, the example provided either joins on `bankaccoun0_` foreign key into `useraccoun1_` and then applies the WHERE to `useraccoun1_`'s primary key. Or in your hand-edited example, it simply matches on `bankaccoun0_` foreign key directly. These queries are semantically equivalent. The foreign key in `bankaccount0_` IS the primary key in `useraccoun1_`. Thus, no extra rows will be brought in nor will any appropriate rows be left out in either situation.

Another question could be about performance. If the database's primary keys are properly indexed (as they should be), then the Spring Data-generated query's WHERE portion should be hitting an index. And the JOIN should also be hitting the same index. So I see little risk in a performance issue. It should quickly find the proper row and not end up generating some huge cartesian product nor risking a full table scan due to do an upper.

Therefore, I don't think there is anything to pursue here. Again, if a query isn't fully optimized, is too complex for Spring Data's query derivation, and appears to be a performance concern, then yes you can fall back to `@Query`. But in this situation I don't see anything to fix.
