### ISSUE TITLE
Use query by example to return a java.util.Stream [DATAJPA-972]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1321]
**[Daniel Imber](https://jira.spring.io/secure/ViewProfile.jspa?name=imberda)** opened **[DATAJPA-972](https://jira.spring.io/browse/DATAJPA-972?redirect=false)** and commented

The query-by-example API is very useful and can (depending on the example) return a large number of results. It would be very useful if this facility allowed returning of a java.util.Stream to easy process results without a potentially large memory footprint.

Perhaps this is possible already buy I've not found this documents or via SO.

The idea would be to do something like:

Example example = ...
repository.findAllStream(example).forEach(...)

---

**Affects:** 1.10.3 (Hopper SR3)

**Comment by gregturn** [comment]
For starters, you can't overload on return type in Java. So it's impossible for us to have:

```java
<S extends T> Iterable<S> findAll(Example<S> example);
<S extends T> Stream<S> findAll(Example<S> example);
```
...in the same interface. So I don't think we're going to do that.

You have two possibilities. One is to extend `CrudRepository` (or just `Repository`) and define your own:

```java
<S extends T> Stream<S> findAll(Example<S> example);
```

I actually tinkered with one of our test cases, implementing this:

```java
public interface UserWithOptionalFieldRepository extends CrudRepository<UserWithOptionalField, Long> {

	<S extends UserWithOptionalField> S saveAndFlush(S entity);

	<S extends UserWithOptionalField> Stream<S> findAll(Example<S> example);
}
```
And it worked just fine after I adjusted my test case consuming a `Stream` instead of a `List`. The alternative is to `.stream()` on your results. 

Of course this heavily depends upon your use case and performance needs. Since you mentioned performance as an issue, know that JPA providers, when we see a `Stream` return type, give us `ScrollableResult`, giving us a little more sanity at consuming the result set than blindly wrapping an in-memory `List` and slapping a `Stream` API on it.

But I don't think we're going to take on managing a completely new variant that is `Stream`-based given you have the tools to fashion your own with things as-is.
