### ISSUE TITLE
The repository countDistinctBy** method generates the wrong sql query [DATAJPA-1036]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1380]
**[Anthony](https://jira.spring.io/secure/ViewProfile.jspa?name=anthofo)** opened **[DATAJPA-1036](https://jira.spring.io/browse/DATAJPA-1036?redirect=false)** and commented

When we use a count query with a distinct:

```java
long countDistinctVersionIdBy*(...)
```

The generated sql is:

```sql
select distinct count(version_id) ..
```

instead of

```sql
select count(distinct version_id) ..
```

The results of the two queries are different, adding a distinct before the count does not change the result, while adding it inside the count can change the result

---

**Affects:** 1.10.5 (Hopper SR5)

1 votes, 1 watchers

**Comment by gregturn** [comment]
This issue is definitely valid. It reveals that `JpaCountQueryCreator` needs its own watch to handle `boolean distinct` than how `JpaQueryCreator`. 

A small patch can fix this from being `select distinct count(distinct ...) ...` to `select count(distinct ...)...`. 

However, this is incomplete, since `countDistinctByXXX()` will still render `select count(distinct u.id) ...`, which has no net benefit. So I went and captured this bigger issue of how Spring Data JPA deals with `DISTINCT` operations in #2525.
