### ISSUE TITLE
Strange version increment using @LastModifiedDate [DATAJPA-1136]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1481]
**[Daniele Renda](https://jira.spring.io/secure/ViewProfile.jspa?name=drenda81)** opened **[DATAJPA-1136](https://jira.spring.io/browse/DATAJPA-1136?redirect=false)** and commented

I created a small test case using Spring Boot 1.5.3, Spring JPA and Hibernate 5.2.10. I created this test case when I noticed strange things in my application using Hibernate envers: I had several rows in audit table with same data. So, also if the entity was unchanged I had a new rows in audit table.

I created then this test case focusing on Hibernate and Spring JPA. I created a simple entity:

```java
 @Entity
@EntityListeners({ AuditingEntityListener.class})
public class TestEntity extends AbstractPersistable<Long> {
    private static final long serialVersionUID = -7939807161238741482L;

    private String name;

    // Trick to start version counting from 1 instead of 0
    @Version
    private int version = 1;

    @LastModifiedDate
    private LocalDateTime lastModifiedDate;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public LocalDateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}
```

Nothing special here; just the AuditingEntityListener that permit to set the latModifiedDate automatically. This is the test case:

```java
 @RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
@TestPropertySource(locations = "classpath:test.properties")
public class HibernateTests {
    private Logger log = LogManager.getLogger();

    @Autowired
    private TestEntityRepository testEntityRepository;

    @Before
    public void setup() {
        testEntityRepository.deleteAll();
    }

    @Test
    public void checkVersionAfterUpdateWithoutChanges() {
        TestEntity testEntity = new TestEntity();
        testEntity.setName("Name");
        testEntity = testEntityRepository.save(testEntity);

        assertEquals(1, testEntity.getVersion());

        // saving again the user without changes
        testEntity = testEntityRepository.save(testEntity);

        assertEquals(1, testEntity.getVersion());

    }

}
```

Note I'm not using `@Transactional` because I want simulate that different transactions make a save of the object. What am I doing? I create a TestEntity object, I saved that and I checked the version is 1. This assertion succedeed. Then I resaved the same object without any changes and I expected Hibernate didn't make any update on the database, instead the assertion fails because it returns 2 as version.

Removing the AuditingEntityListener from my entity instead the test passes! Is this a desired behaviour?
I debugged Hibernate code until arrive to the point where there is the problem: TypeHelper.findDirty(). As expected the method find the lastModifiedDate is changed (it return an array with the index of the field changed). Should't lastModifiedDate be updated after the dirty check control? The object should be updated only if some property is changed, but change the modification date will make the object always elegible to be updated in the databse

---

**Affects:** 1.11.4 (Ingalls SR4)

1 votes, 2 watchers

**Comment by vaibhavrodage** [comment]
I have come to the same situation. Did we get any solution?

**Comment by schauder** [comment]
One might argue that when you call `save` it is fair to assume that you actually want it saved and therefore it is correct to increase the version and set a modified date.

In any case, this seems to be based in the behaviour of the JPA implementation. 
They seem to get some lee way in the JPA specification about their exact behaviour in this situation.
It is not clearly specified if a call to `EntityManager.merge` with an unmodified managed entity should trigger an update event or not.

But that is what seems to happen. 
Spring Data JPA uses an entity listener for setting the auditing data and when you call save with an already saved and unchanged entity the implementation will call `EntityManager.merge`.
And that seems to trigger the event.

I don't see a way how Spring Data can change this, apart from not calling save, when there is nothing to be saved.

**Comment by natami** [comment]
> I have come to the same situation. Did we get any solution?

Do you guys also use hibernate-enhance-maven-plugin or the like in your applications?

**Comment by ttl771** [comment]
The test from the op won't have a predictable outcome and it's not a Spring JPA issue. The default sql TIMESTAMP has not enough precision to handle nanos. Hibernate synchronizes itself with the database on update. So if you try to save a timestamp with nanos > 0 rounding will take place and hibernate will consider the rounded value as the "previous state". But this change won't be synchronized back to your entity. On the next dirty check hibernate compares the previous state with the rounded value against the current state which - you guessed it - contains the unrounded value of the same time (auditing did not take place yet!). This is why the dirty-check returns true although nothing has been changed.  If stars align and you hit a time with nanos=0 by chance your test will suddenly have a different result which is exactly what happened to one of our unit tests (before that i suspected that save() always causes an update like stated in previous comments). Another way to reliable change the observed behavior is to switch from LocalDateTime to Long which makes sense since the Long value represents milliseconds and can't contain nanoseconds by definition. 

For verification without changing the data type you can mock the DateTimeProvider and return a fixed LocalDateTime value. Try this with and without nanoseconds and you should see the behavior change. At least this is how i could reproduce it.
To fix this issue you can simply add a custom column definition extending the precision of TIMESTAMP from 6 to 9:


```java
 @LastModifiedDate
 @Column ( columnDefinition="TIMESTAMP(9)" )
 private LocalDateTime lastModifiedDate;
```

I know the ticket is quite old and closed but maybe this helps other people stumbling across the same observation as this behavior still occurs in hibernate 6.1.7.
