### ISSUE TITLE
repository.save() does not update the returned entity when fields are marked updatable=false [DATAJPA-1421]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1735]
**[Jason Bodnar](https://jira.spring.io/secure/ViewProfile.jspa?name=jcbodnar)** opened **[DATAJPA-1421](https://jira.spring.io/browse/DATAJPA-1421?redirect=false)** and commented

I'm using Spring Data's annotations to add auditing data to my entities when they are saved or updated. When I create the entity the createdBy, createdDate, lastModifiedBy and lastModifiedDate get set on the object returned by repository.save(). Unfortunately, when I call repository.save() to update an existing entity the object returned does not have the createdBy and createdDate set. All the fields are set correctly in the database though

---

**Affects:** 2.0.10 (Kay SR10)

**Reference URL:** https://github.com/jcbodnar/auditing-example

**Comment by kilaka** [comment]
My thought is that when a field is marked `updatable=false`, I would expect the original value used in the audit/merge process.
Another thought is for another annotation to always load the original values when a field is `updatable=false`, but this feels like it should be the default behavior.

> **[Jens Schauder](https://jira.spring.io/secure/ViewProfile.jspa?name=schauder)** commented
> 
> This behavior is not caused by the auditing feature setting values or not. You are essentially resetting the fields to `null`.
> 
> Here is what is happening:
> 
> 1. You save the first instances _i1_. Fields get set and since your transaction only spans the call to the repository changes get flushed as expected.
> 2. You create a fresh instance _i2_. That instance doesn't have any of the auditing fields set.
> 3. You invoke `save`.
>    a) Which does a JPA `merge`, which loads the data from the original instance, creates a new one _i3_. Then it copies the data from _i2_ over into _i3_. The auditing fields are now `null` since that are the values from _i2_.
>    b) The auditing listener kicks in and updates the `lastModified` and `lastModifiedBy` fields. It does not change the `created...` fields since it's not a new instance, but an update, so those stay `null`.
>    c) The changes get flushed to the database, but not the `created...` fields since those are annotated with `updatable=false` so they never get updated.
> 4. you compare the `created...` fields of _i3_ (`null`) with those of _i1_ (`not null`) and the test fails

**Comment by agarcia-te** [comment]
@schauder 

I wonder if it'd be helpful to focus on this from a different perspective.

Regardless of the reason why this issue occurs, the issue is still valid.

The purpose of this library is as follows:

```
Spring Data provides sophisticated support to transparently keep track of who created or changed an entity and when the change happened.
```

Extract from: https://docs.spring.io/spring-data/jpa/reference/auditing.html

Created fields should not be allowed to be updated otherwise they are no longer fulfilling its purpose.

I disagree with the following statement:

```
because you set them to null and also made the updatable=false, so this is exactly what should happen.
```
`updatable=false` means the field shouldn't be updated (included in `update` statements), it does not imply that it cannot be read.

That being said, even if we assume that to be true. If this is not the way to achieve this functionality, I believe an alternative should be provided.

If we have to either:
- manually be loading and and setting the created fields 
- manually validating / rejecting changes to created fields

Then the library is no longer `transparently keeping track of who created or changed an entity` is it?

**Comment by sen-harshit03** [comment]
I agree with @agarcia-te. The primary purpose of auditing features is to ensure users see accurate timestamps when entities are created or updated. 
In our API, when we create an entity and return the saved entity as a response, fields annotated with `@LastModifiedDate` and `@LastModifiedBy` are intended to remain empty in the database because we have configured them with `insertable = false`. However, after saving the entity, these fields are unexpectedly populated in the returned object from the `save()` operation. 
As a result, the API response contains incorrect values for these fields. This discrepancy means that the frontend might display a value for last modified date and last modified by, but in the database, it remains null as expected. Such inconsistencies can lead to data integrity issues.
