### ISSUE TITLE
apply Queryutils.applyAndBind() on limited sized entities collection parts [DATAJPA-1422]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1736]
**[Balazs Torma](https://jira.spring.io/secure/ViewProfile.jspa?name=torel)** opened **[DATAJPA-1422](https://jira.spring.io/browse/DATAJPA-1422?redirect=false)** and commented

The length of the SQL statement built by QueryUtils.applyAndBind() grows with the collection size passed in (entities). That is, if the collection contains many elements, the statement can get so long that the database can not process it anymore.

 

This can lead to nasty exceptions that occur whenever entity size is big (which is data dependent -> hard to analyse in production environments where data not available)

 

QueryUtils.applyAndBind() is called for example from JPARepository.deleteInBatch()

 

A solution could be to implement a chunker (slicer), that calls QueryUtils.applyAndBind() on subsets of the whole entities collection repeatedly.

ps.: user of QueryUtils.applyAndBind() can of course wrap it in a chunker but it would be nice and less error prone to have this wrapper in the core libraries

 

---

**Affects:** 2.1 RC2 (Lovelace), 2.0.10 (Kay SR10)

**Comment by gregturn** [comment]
I'm not sure how Spring Data JPA is supposed to analyze this, sitting in between user code and the JPA provider, and come up with a suitable slice. 

Spring Data is a generic processor and may lack context from user code. It also probably can't identity semantics from the JPA provider like "is this PostgreSQL", and know what the query limits are. So it can't pick a suitable "size" to split things up. We certainly don't want to switch to one-by-one, because performance will suffer.

It's possible for the code invoking JpaRepository.deleteAllInbatch(Iterable<T> entities) to send in a slice at a time. There's a whole world available with Java 8, where you can take an `Iterable`, convert it to a Java 8 `Stream`, then collect them together using `Collectors.partitioningBy(...)`, giving you a map of `List` objects, each of which could be routed into `deleteAllInBatch`.

I'm afraid any sort of chunking smarts should be handled closer to application code. We already provide the means to delete a "chunk" via batch with the `Iterable<T>` API discussed in this ticket.
