### ISSUE TITLE
Add support for derived 'between' queries using Range [DATAJPA-1511]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1823]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAJPA-1511](https://jira.spring.io/browse/DATAJPA-1511?redirect=false)** and commented

Right now the `Between` keyword for dereived queries translates to `>=` and `<=`. Usage of `Range` would allow the user to customize boundaries as needed

---

**Issue Links:**
- [DATACMNS-1488](https://jira.spring.io/browse/DATACMNS-1488) Please add LeftOpenBetween, RightOpenBetween and OpenBetween as supported query keywords

- [DATAMONGO-2072](https://jira.spring.io/browse/DATAMONGO-2072) Add support for derived 'between' queries using Range

**Comment by gregturn** [comment]
Spring Data JPA now uses JPA's `between()` operator...

```java
				case BETWEEN:
					ParameterMetadata<Comparable> first = provider.next(part);
					ParameterMetadata<Comparable> second = provider.next(part);
					return builder.between(getComparablePath(root, part), first.getExpression(), second.getExpression());
```
...so I'm not sure this request is still valid.

**Comment by gregturn** [comment]
@mp911de How should we do this?

I had thought that:

```java
List<User> findByAgeBetween(Range<Integer> ages);
```
...was the pattern to deploy, but this doesn't work with Spring Data Commons, since `BETWEEN` is hard-coded to accept two arguments.

Are you suggesting that a user would assemble a `Range` object and then feed two `Range.Bound` arguments to the query, and ONLY if they are both inclusive, to use JPA's `between` operator? Anything else pivots to the greater/less than options?

**Comment by gregturn** [comment]
I have tried sprinkling in a way to parse `Range.Bound` conditions, but I'm not sure I see how to do that. I can dereference a boundary's value like this:

```java
public <T> Query setParameter(Parameter<T> param, T value) {

    if (value instanceof Range.Bound<?> bound) {
        T boundedValue = (T) bound.getValue()
                .orElseThrow(() -> new IllegalArgumentException("Boundary can't be null!"));
        return unwrapped.setParameter(param, boundedValue);
    }

    return unwrapped.setParameter(param, value);
}
```
...but this doesn't address the issue of need to wait until this phase to pick the which function to apply.

I drafted this code over on the `BETWEEN` keyword:

```java
case BETWEEN:
    ParameterMetadata<Comparable> first = provider.next(part);
    ParameterMetadata<Comparable> second = provider.next(part);

    Function<Boolean, Predicate> lowerBoundFunc = inclusive -> inclusive //
            ? builder.greaterThanOrEqualTo(getComparablePath(root, part), first.getExpression()) //
            : builder.greaterThan(getComparablePath(root, part), first.getExpression());

    Function<Boolean, Predicate> upperBoundFunc = inclusive -> inclusive //
            ? builder.lessThanOrEqualTo(getComparablePath(root, part), second.getExpression()) //
            : builder.lessThan(getComparablePath(root, part), second.getExpression());

    // need to delay this part until arguments are supplied
    Predicate lowerBound = lowerBoundFunc.apply(true);
    Predicate upperBound = upperBoundFunc.apply(true);

    return builder.and(lowerBound, upperBound);
```
...but this part of query derivation appears to want a more static, fixed configuration. The arguments return a pure JPA `Predicate`. I wonder if it's possible to craft a wrapper of that and sneak in the functions. Then access them during execution?

**Comment by gregturn** [comment]
I tried implement a type of wrapper where we could capture the function above into a Hibernate `SqmPredicate`, with hopes that i could lazily invoke it at the time of execution.

```java
case BETWEEN:
    ParameterMetadata<Comparable> first = provider.next(part);
    ParameterMetadata<Comparable> second = provider.next(part);

    RangeBoundaryHibernatePredicate lowerRangeBoundaryExpression = new RangeBoundaryHibernatePredicate(
            inclusive -> (SqmPredicate) (inclusive //
                    ? builder.greaterThanOrEqualTo(getComparablePath(root, part), first.getExpression()) //
                    : builder.greaterThan(getComparablePath(root, part), first.getExpression())));

    RangeBoundaryHibernatePredicate upperRangeBoundaryExpression = new RangeBoundaryHibernatePredicate(
            inclusive -> (SqmPredicate) (inclusive //
                    ? builder.lessThanOrEqualTo(getComparablePath(root, part), second.getExpression()) //
                    : builder.lessThan(getComparablePath(root, part), second.getExpression())));

    return builder.and(lowerRangeBoundaryExpression, upperRangeBoundaryExpression);
```

I thought that if we wrapped this function inside some type that could emulate a Hibernate `Predicate`, we could somehow wait until execution time to make the choice.

```java
private static class RangeBoundaryHibernatePredicate implements SqmPredicate {

    private Function<Boolean, SqmPredicate> function;

    private SqmPredicate delegate;

    private RangeBoundaryHibernatePredicate(Function<Boolean, SqmPredicate> function) {
        this.function = function;
    }
    ...delegate functions...
}
```

My hope was that an extra method call where the inclusive flag would update the `delegate` as needed (or something like this). Turns out, this does NOT work since `JpaQueryCreator.toPredicate()` invokes a delegate function during query creation.

It REALLY looks like we can't delay the inclusive/exclusive setting until execution time. Hibernate (and possibly EclipseLink as well) really seem to like generating the final queries up front for optimization. Holding out for a user-supplied switch like this doesn't appear possible without subverting Hibernate.
