### ISSUE TITLE
5.3.9. Applying Query Hints unclear about JPA query hints [DATAJPA-1790]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2085]
**[Chealer](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50525)** opened **[DATAJPA-1790](https://jira.spring.io/browse/DATAJPA-1790?redirect=false)** and commented

I do not understand section 5.3.9. Applying _Query Hints_. Could this describe what JPA query hints are, or perhaps link to documentation for these or documentation about @`QueryHint?`

---

**Affects:** 2.3.4 (Neumann SR4)

**Reference URL:** https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-hints

**Comment by Chealer** [comment]
Can this ticket be reopened?

**Comment by schauder** [comment]
I'd rather not. I just searched for `jpa query hints` and the two top results look pretty good. But we certainly won't link to those since they are just blog articles by various people. Whom should we link to? The official documentation though is pretty anemic, so a link wouldn't help.

And also query hints aren't even a main pain point when it comes to not understanding JPA: lazy loading, caching and dirty tracking is a much bigger problem and again can't be solved with a simple link or a sentence or two, but with a quick internet search.

**Comment by Chealer** [comment]
Thank you Jens
I can't answer that question, but if you think the page should link to the official documentation, I would think a link should be added regardless of its current state. Once the official documentation is fine, Spring Data JPA's will become fine (or at least better) too.

**Comment by Chealer** [comment]
If the issue tracked is not about to be solved or mitigated, can someone at least reopen this ticket so that the issue is properly tracked?

**Comment by schauder** [comment]
The issue is closed with status "declined" and as such properly tracks the issue.

**Comment by Chealer** [comment]
@schauder there is no such status as "declined". While issues are related to requests, this ticket is not a request, but an issue report.
