### ISSUE TITLE
Use a constant hashCode for entities instead of the database-generated id hashCode [DATAJPA-1823]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2112]
**[Patrice Blanchardie](https://jira.spring.io/secure/ViewProfile.jspa?name=inisos)** opened **[DATAJPA-1823](https://jira.spring.io/browse/DATAJPA-1823?redirect=false)** and commented

Using the database-generated id hashCode leads to problems with state transitions that have been described several times, by Vlad Mihalcea amongst others:

https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/

Using a constant is generally a better choice, so I suggest `getClass().hashCode()`

---

**Affects:** 2.4.1 (2020.0.1)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/437

**Comment by jonenst** [comment]
> Constant hashCode is still compatible with HashMap and starting from Java 8 (with the new HashMap implementation) the worst-case when all hashCodes are the same is not O(n) anymore but O(log n).

@pblanchardie For the record, this statement is oversimplifying it. While buckets are switched to self balanced binary search trees (a.k.a. treesets) after the default threshold of 64 items instead of lists, the key of the search tree used is the hash, and then the class, and then the identityhashcode.
So `contains` on an element for which this exact instance is already in the set with the is indeed O(log n), but for elements that are not present at all or for which the element in the set is not the same instance are O(n). Same for adding elements, the performance depends on whether the reference is already in the set or not.
