### ISSUE TITLE
JPA StoredProcedureQuery - Register boolean type out param [DATAJPA-1836]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2124]
**[Praveen](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50830)** opened **[DATAJPA-1836](https://jira.spring.io/browse/DATAJPA-1836?redirect=false)** and commented

Im using JPA stored procedure query to invoke a oracle 12c stored procedure which has 3 in and 3 out params , out of which one param is of type BOOLEAN.
When i set the type as Boolean

entityManager.createStoredProcedureQuery(SPName) . . . **.registerStoredProcedureParameter("param_name", Boolean.class, ParameterMode.OUT)**

Im getting the following error

**Caused by: java.sql.SQLException: Invalid column type: 16**

I read from few other posts(https://stackoverflow.com/a/55413745/8869899) that boolean is supported by jdbc driver from oracle version 12.2 and OracleType.PLSQL_BOOLEAN is the type to be used to bind the boolean Stored proc parameter. So i had tried something like the below

entityManager.createStoredProcedureQuery(SPName) . . . .**registerStoredProcedureParameter("param_name", OracleType.PLSQL_BOOLEAN.getClass(), ParameterMode.OUT)** .setParam(...);

But it too doesnt work. I'm Getting the below error

PLS-00306: wrong number or types of arguments in call to 'SPName'

Is the approach im following correct or is there any other way to access this stored procedure?

Pls note, I cant add new/change the stored procedure as it is a migration project and DB changes are not allowed. Appreciate your help!

---
No further details from [DATAJPA-1836](https://jira.spring.io/browse/DATAJPA-1836?redirect=false)

**Comment by odin568** [comment]
Problem is that JPA/Hibernate finally sends 
`2021-11-19 11:44:44.564 TRACE 4744 --- [QueueListener-1] o.h.type.descriptor.sql.BasicBinder : binding parameter [p_xxxxxx] as [BIT] - [true]`
and not OracleTypes.PLSQL_BOOLEAN

```java
@Repository
public interface MyRepository extends JpaRepository<MyEntity, Long> 
{
    @Procedure(procedureName = "PKG.SP_DOWORK")
    void setDoWork(@Param("p_flag") boolean flag);
}
```

**Comment by gregturn** [comment]
According to https://stackoverflow.com/a/17162349/28214, if you're using the OCI-based drive, then there is no support for `java.lang.Boolean` mapping to PL/SQL `BOOLEAN`. Of course, I don't know which variant of the Oracle driver you're using.

But since we're in the process of supporting JPA and not database vendors specifically, I don't see a generic solution that we can offer. You may have to either alter the stored procedure to work with supported JDBC types, or you may have to interact with the stored procedure through other means.

This is clearly some Oracle-specific issue.
