### ISSUE TITLE
How to map list of custom objects

### ISSUE THREAD

**Issue by artem-kurilko** [spring-projects/spring-data-jpa#2138]
I have postgres rest api application, and need to retrieve all values from customFunction(). I created projection and everything works except returning list of Friend.class instances.

How I can map list of objects in spring data jpa?

Full code:
```
@Data
@AllArgsConstructor
class Person {
    private String name;
    private String surname;
    private List<Friend> friends;
}

interface PersonProjection {
    String getName();
    String getSurname();
    List<Friend> getFriends();
}

@Entity
@Data
@AllArgsConstructor
class Friend { 
    private String name;
    private String surname; 
}

interface PersonRepository {
    @Query(value = "select * from customFunction()", nativeQuery = true)
    List<PersonProjection> callFunc();
}
```

**Comment by mp911de** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
