### ISSUE TITLE
SpecificationComposition reversed predicates

### ISSUE THREAD

**Issue by rideliner** [spring-projects/spring-data-jpa#2146]
It appears that `lhs` and `rhs`  were reversed in 25924d89.

https://github.com/spring-projects/spring-data-jpa/blob/master/src/main/java/org/springframework/data/jpa/domain/SpecificationComposition.java#L54

This causes `spec1.and(spec2)` to result in `spec2 and spec1`.

**Comment by schauder** [comment]
Does this matter? The order of execution is determined by the execution plan created by the database, not by the order of statements in the SQL statement, isn't it?

**Comment by mp911de** [comment]
The issue affects also `OR` concatenation.

**Comment by pgv** [comment]
This also fixes https://github.com/spring-projects/spring-data-jpa/issues/1309. It's not really a fix though, cause if you compose two specifications in the wrong order, let's say you add a condition `parent.name = 'x'` first and then `inner join fetch parent`, the first condition won't be able to find the parent join and create a new one (or throw an error, I don't remember). I have a lot of old code with the specifcations with conditions first and specifications with joins last because of this very issue. In this version I have to reverse those lines. I would like to work on a better composition implementation, but it's an old issue and don't have the time right now. I guess I'll just move my joins on top of my conditions and move on. There is no easy solution with the current implementation.
