### ISSUE TITLE
Entity with Embedded member the left outer join is not part of query

### ISSUE THREAD

**Issue by eranf91** [spring-projects/spring-data-jpa#2209]
I have the following code, work perfectly fine with springboot 2.4.3, but fails with 2.4.4
The bug is relate to springboot data jpa
I have the following class:

```
@Entity
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class User {
    @Id
    @GeneratedValue(strategy = IDENTITY)
    Long id;

    @Embedded
    Addition addition;

    @Embeddable
    @Getter
    @AllArgsConstructor
    @NoArgsConstructor
    @Builder(toBuilder = true)
    public static class Addition {

        @Column(table = "user_addition")
        String name;
    }
}
```

Then having the following repository:

```
public interface UserRepository extends JpaRepository<User, Long>{
    boolean existsByAddition_Name(String name);
}
```
In springboot 2.4.3
The query generated from calling: existsByAddition_Name
include the left outer join of user_addition table

In springboot 2.4.4
The query generated from calling: existsByAddition_Name
**Does not** include the left outer join of user_addition table

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

Could you also test against an older version of Hibernate to verify whether the issue is related to Hibernate? If that's indeed a Spring Data problem, please provide the queries that you see and the actual query that should be issued.

**Comment by eranf91** [comment]
[issue models.tar.gz](https://github.com/spring-projects/spring-data-jpa/files/6432764/issue.models.tar.gz)
I attached a tar gz include to models:
each module include a test
1. spring-data-user-1: uses springboot 2.4.3 and test running successfully.
2. spring-data-user-2: uses springboot 2.4.5 and test running with failure
The failure is caused because of missing left outer join.
I do not know what are the changes that causes the defect, therefor I can not determine if this is a hibernate bug or not.
All I know is upgrade springboot (include the springboot data) break backward compatibility

**Comment by schauder** [comment]
That is some weird mapping. You are using `@Embedded` and `@Embeddable`, which is normally used to store fields from a secondary class in the same table as the primary class, but then use the `@Column` annotation to actually store it in a different table.

May I ask why you are doing this?

Anyway, it does work with older versions and breaks with new ones and this seems to be independent of the Hibernate version, so it seems to be a bug.

**Comment by schauder** [comment]
The reason we don't get a join is a query is:
- the embedded entity uses a secondary table
- we actually request a join when constructing the query
- Only a single field, not the full entity is selected.

This combination hits what I consider a bug in Hibernate https://hibernate.atlassian.net/browse/HHH-14590

Previous versions of Spring Data didn't request a join.

Given that the circumstances are rather special, der root cause seems to be a Hibernate bug and a query annotation should work as a workaround I don't think we will patch this, but I'll discuss with the team.

**Comment by schauder** [comment]
There is a reproducer for the behaviour on JPA level: https://github.com/schauder/issue-HHH-14590-missing-join-with-embeddable.

**Comment by eranf91** [comment]
> That is some weird mapping. You are using `@Embedded` and `@Embeddable`, which is normally used to store fields from a secondary class in the same table as the primary class, but then use the `@Column` annotation to actually store it in a different table.
> 
> May I ask why you are doing this?
> 
> Anyway, it does work with older versions and breaks with new ones and this seems to be independent of the Hibernate version, so it seems to be a bug.

According to your reply I understood that I used the annotations incorrectly, I removed the Embeddable annotation completely
Deleted the nested class, and put its fields under the 'User' class, the field from the second table I put in the user class, and used: @Column(table = "user_attribute)
Then the existsBy spring data query worked perfectly.

To summarize:
1. I had a misused of Embeddable annotation.
I fixed my specific issue by fixing my own code.
2. I still think there is a bu with Embeddable when using it correctly, might cause the missing join when its needed.
