### ISSUE TITLE
Enhancement: support for Hibernate reactive

### ISSUE THREAD

**Issue by yaakov-berkovitch** [spring-projects/spring-data-jpa#2211]
Is there any plan to support [Hibernate Reactive project](http://hibernate.org/reactive/) working with the [Vert.x Reactive DB driver](https://vertx.io/docs/vertx-pg-client/java/)

We started a project using this stack and Spring boot, but it will be very valuable to be able to use also spring-data.

Thanks

**Comment by mp911de** [comment]
Hibernate Reactive isn't using the JPA API, rather they introduced new API that is specific to Hibernate. If you're looking for reactive SQL support, take a look at [Spring Data R2DBC](https://github.com/spring-projects/spring-data-r2dbc/) that integrates with reactive drivers following the R2DBC standard.

**Comment by yaakov-berkovitch** [comment]
Thanks @mp911de for your answer. I didn't know they defined a new API. I found it very promising because we already have a big knowledge around regular Hibernate, but we are moving to reactive programing. The problem is that RD2BC has some missing features like lazy loading, support for association like one-to-many, caching and more.

**Comment by brianpreuss** [comment]
Support for Hibernate Reactive would have been very nice

**Comment by UkonnRa** [comment]
+1, supporting Hibernate Reactive would be nice, since R2DBC does not support QueryDSL yet.

**Comment by ah1508** [comment]
+1 , the big advantage is the support of the JPA mapping. The reactive session API is not JPA compliant but it does not matter since spring data is an abstraction on top of it. However it would be a new spring data module.

Hibernate reactive uses Mutiny but a converter helps expose `Mono` and `Flux` instead of `Uni` and `Multi`. Here is a basic implementation of `ReactiveSortingRepository` with Hibernate reactive : [spring-data-hibernate-reactive.zip](https://github.com/spring-projects/spring-data-jpa/files/7781430/spring-data-hibernate-reactive.zip)

* with `SessionFactory` auto configuration and second level cache filling on startup
* without `ReactiveTransactionManager`.
 
It also uses vert.x database driver. It results in two event loops if used with spring-webflux but not with `vertx-spring-boot-starter-http`.

Query by example and derived queries handling could be taken from spring-data-jpa (except operation that involves a count query).

The tests use postgresql  (docker-compose.yml included in the project). Only the delete by entity and entities fails since `find` and `remove` are not called with the same `Session` because the test method execution is not surrounded by a transaction.

Lazy loading is obviously not supported but `join fetch` and eager loading (with second level cache) helps to handle most of the relations loading use cases. 

For lazy relations, an interesting feature could be : 

```java
Mono<T> findById(ID id, String... relationsToFetch);
```

Usage : 
```java
Mono<Blog> mono = repository.findById(1, "posts");
```
Since `Mutiny.fetch` allows lazy loading it is maybe possible to declare a method like this, which brings type safety.

```java
Mono<T> findById(ID id, Function<T, ?>... relationsToFetch);
```

Usage : 
```java
Mono<Blog> mono = repository.findById(1,  x -> x.getPosts());
```

However loading 1-n and n-n relations in a single query results in n lines returned from the database (and Cartesian product if several 1-n or n-n relations are fetched).

**Comment by hantsy** [comment]
@ah1508  I have added [Mutiny support to Spring framework](https://github.com/spring-projects/spring-framework/pull/27331) and Spring Data Commons, but Spring Data Commons did not accept the Mutiny variants of the Repository interface.

Hibernate Reactive reused the annotations of JPA. 

Compared to the existing Hibernate support in Spring, when adding Hibernate Reactive the biggest change is providing a reactive SessionFactoryBean instead, and should support Reactive transaction.

**Comment by hantsy** [comment]
My example project for adding Hibernate Reactive to Spring manually, https://itnext.io/integrating-hibernate-reactive-with-spring-5427440607fe.

**Comment by Sam-Kruglov** [comment]
Hibernate Reactive is not against introducing R2DBC into their codebase but are not willing to put in the work themselves to do that. However, they added an extension point that allows users to experiment with integrating alternative reactive database drivers. 

see https://github.com/hibernate/hibernate-reactive/issues/76#issuecomment-633063114

**Comment by hantsy** [comment]
In fact, I think Hibernate Reactive can reuse some work of the existing Spring Hibernate support and Spring Data JPA. 

Hibernate Reactive is based on the Vertx Reactive Drivers which is incompatible with R2dbc, and R2dbc specification is mainly maintained by the Spring guys.

Vertx Reactive Drivers are already adopted in Vertx, Quarkus, Hibernate Reactive and Micronaut SQL module.
