### ISSUE TITLE
Native query with RETURNING clause ignores @Modifying

### ISSUE THREAD

**Issue by Aloomenon** [spring-projects/spring-data-jpa#2270]
Hello everyone!

I found a problem with `@Modifying`  and `nativeQuery = true` for queries with PostgreSQL `RETURNING` clause.
Look through an example:
```
    @Modifying
    @Query(
        value = ""
            + "UPDATE simple "
            + "SET field = 'updated' "
            + "WHERE id IS NOT NULL "
            + "RETURNING id",
        nativeQuery = true
    )
    List<Integer> updateAll();
```

When I call `updateAll()` method `@Modifying` is ignored because of [Executon initialization order](https://github.com/spring-projects/spring-data-jpa/blob/acf01b6c7140a56cd1c3caa67409b4d4f922937d/src/main/java/org/springframework/data/jpa/repository/query/AbstractJpaQuery.java#L101).
BTW the query is working fine.

Maybe an exception should be thrown in such cases?

**Comment by schauder** [comment]
Do you get an exception? Or what is actually happening? What does happen if you don't use `@Modifying`? 

Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by Aloomenon** [comment]
`
Do you get an exception?
`
No, I don't.
Actually, the query is working fine, but there's one moment:
If you call it in transactional context with cached Entity (In L1 cache for example), changes will disappear.
Because cache will flush at the end of the transaction.

`@Modifying` In this query is ignored, so you can use this kind of query without this annotation (which is also incorrect IMHO).

I provide a small project that demonstrates how it works with/without transaction and annotation.
https://github.com/Aloomenon/Spring-data-jpa-Modifying-issue-demo

**Comment by joshiste** [comment]
Just to add my 5 cents on this:

I wanna do a `update ... returning col` (where col is of type uuid) . This yields the following exception:

`java.lang.IllegalArgumentException: Modifying queries can only use void or int/Integer as return type! Offending method: ...`

I'd love to see support for this in spring data jpa

**Comment by joshiste** [comment]
Just to add my 5 cents on this:

I wanna do a `update ... returning col` (where col is of type uuid) . This yields the following exception:

```
java.lang.IllegalArgumentException: Modifying queries can only use void or int/Integer as return type! Offending method: ...
```

I could use a native query without the `@Modifying` but then I currently don't know how to clear/flush automatically

**Comment by schauder** [comment]
I'm not sure what you mean by "`@Modifying` In this query is ignored". 
Not sure what you mean by this.
Queries (DQL) get executed in a different way by JPA than updates, deletes and inserts (DML) and also DDL statements.
Spring Data JPA uses the `@Modifying` annotation to identify DML statements and execute them accordingly.
I'm honestly not sure if a update...returning statement counts as DML or DQL but it seems JPA can handle it either way.

> If you call it in transactional context with cached Entity (In L1 cache for example), changes disappear.
Because cache will flush at the end of the transaction and erase all changes.

What you are seeing is normal JPA behaviour.
You update the database which JPA does know nothing about. When you call `getById` in the same transaction it returns the instance from the 1st level cache without accessing the database.

There are many question on SO about this. E.g. https://stackoverflow.com/questions/33825429/spring-data-refresh-entity-after-manual-backend-query-update

**Comment by Aloomenon** [comment]
I agree that JPA doesnt know anything about returning clause and "parsing" it as select query but on other hand it is unpredictable that @Modifying wont work. I think there should be an exception or atleast warning.

Perhaps we can clarify this case in classification and throw an exception similar to updating without @Modifying?

**Comment by nkhalis** [comment]
Same for me, I have the same issue ...
