### ISSUE TITLE
Postgres Search_Path support?

### ISSUE THREAD

**Issue by RudiX** [spring-projects/spring-data-jpa#2272]
is postgres search_path feature supported by jpa? For example if you specify seach_path like "tenant1, public", is it possible for jpa to search for specific entities using this search_path? the  goal is to change searcH:path dynamically

**Comment by schauder** [comment]
> is postgres search_path feature supported by jpa?

No, it is not. And since it is highly database specific it won't get special support by Spring Data JPA either. 
You can always write a [custom method](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-implementations), that takes a search path and sets it for the current session using JDBC.

Just for clarification: https://stackoverflow.com/questions/42470060/spring-data-jdbc-spring-data-jpa-vs-hibernate
If you want to suggest a change to the JPA specification see https://github.com/eclipse-ee4j/jpa-api/issues
