### ISSUE TITLE
Spring data does not populate not null id field in a Kotlin data class

### ISSUE THREAD

**Issue by johnowl** [spring-projects/spring-data-jpa#2278]
I have this data class

```kotlin
data class User(
    val id: String = "",
    val username: String,
    val password: String,
    val createdAt: LocalDateTime,
    val updatedAt: LocalDateTime
)
```

If a call the repository save method, the id field is not populated with the inserted id, it just works if I change the field to nullable.

**Comment by mp911de** [comment]
In Spring Data JPA, JPA handles all object mapping and conversion aspects hence all mapping and conversion is subject to the JPA specification and the actually used implementation. JPA doesn't support immutable entities in the first place. Please also note that data classes aren't proper entities because of their comparison semantics.
