### ISSUE TITLE
Orderings applied in Specification will be overridden by the sorted Sort in Pageable

### ISSUE THREAD

**Issue by KeroZhai** [spring-projects/spring-data-jpa#2337]
## Steps to reproduce
Please take a look at the following pseudo code:

``` Java
Specification specification = (root, criteriaQuery, criteriaBuilder) -> {
    ...
    criteriaQuery.orderBy(...); // Apply some orderings
    ...
};//
Pageable pageable = ...; //  With valid Sort too

repository.findAll(specification, pageable);
```

## What is expected
Orderings applied in Specification and Pageable are combined together and both take effect.

## What is actually happening
Orderings applied in Specification got overridden.

## Supplement
Here is what I've found:

The `SimpleJpaRepository.getQuery(Specification, Class, Sort)` method will check whether the sort extracted from Pageable is sorted or not, if true, then turns it into `javax.persistence.criteria.Order`s and `CriteriaQuery.orderBy(Order)` method gets called. However, `CriteriaQuery.orderBy()` method will _replace the previous ordering expressions_, which are applied in the `Specification`.

**Comment by KeroZhai** [comment]
In fact I'm not sure if it is a bug or by design. I'm now using a workaround to avoid this, but it might be better to have it implemented in Spring Data JPA.

**Comment by schauder** [comment]
This is by design. A `Specification` is intended as an abstraction of a WHERE-clause. 

That said we are not against combining sorting from specification and pageable, but there is a technical problem:
Can we even obtain the ordering from a specification? I'm honestly not sure about that, but more important for now:
How should. we combine them: specification first, then pageable, or the other way round? Or even a more complex combination?

And you already can combine the two by using the `Pageable` in your `Specification` incorporate the ordering there, or vice versa.

Do you agree? Do you have a better answer to the questions stated?
