### ISSUE TITLE
Allow customizing Querydsl template

### ISSUE THREAD

**Issue by eljo** [spring-projects/spring-data-jpa#2362]
There appears to be no clean way to use a custom QueryDSL `JPQLTemplates` class when creating a query: `Querydsl#createQuery` is hardcoded to use either `EclipseLinkTemplates`, `HQLTemplates` or the default. It'd be great if the template could be customized there, or the method easily overridden.

**Use case**

We need to emit SQL that calls the unaccent Postgres function when using `StringExpression::startsWithIgnoreCase`. The customized template achieves that by overriding `Ops.STARTS_WITH_IC`. This is then usable in a custom repository implementation by injecting the `EntityManager` and creating a new JPAQuery: `new JPAQuery<>(entityManager, new SomeOverridenTemplate())` -- but when using `QuerydslJpaPredicateExecutor` the `JPAQuery` is generated within spring-data-jpa itself.
(If there's a cleaner alternative to do so, I'd be happy to hear :)

**Comment by mp911de** [comment]
`QuerydslRepositorySupport.getQuerydsl()` is `protected` so that you can return a customized subclass of `Querydsl`. Right now, `Querydsl` in `QuerydslJpaPredicateExecutor` cannot be customized. We could introduce there a template method to create a customized `Querydsl` instance. However, you would then need to contribute a customized `QuerydslJpaPredicateExecutor` fragment to your application which requires a more invasive configuration of the repository factory or through a fragment interface.

**Comment by eljo** [comment]
Thanks! `QuerydslRepositorySupport` didn't do the trick (unless of course I'm missing something) as we need this in a `QuerydslBinderCustomizer`. Went with a workaround similar to https://stackoverflow.com/questions/53083047/replacing-deprecated-querydsljparepository-with-querydsljpapredicateexecutor-fai though without the `CrudMethodMetadata` as we don't (currently) use query hints -- but it's a rather nasty hack that heavily relies on current behavior of the `QuerydslJpaPredicateExecutor` internals:

* Override `JpaRepositoryBean`
* Override `JpaRepository`
* Override `QuerydslJpaPredicateExecutor`
* Override `Querydsl`

With all of that out of the way the template can be provided:
```
@Override
 public <T> AbstractJPAQuery<T, JPAQuery<T>> createQuery() {
        return new JPAQuery<>(em, new OurCustomTemplate());
 }
```

A supported way to provide that template would be greatly appreciated here :)

**Comment by gregturn** [comment]
In a nutshell, you would need the ability to swap out/replace `AbstractJPAQuery<?, ?> QuerydslJpaPredicateExecutor.doCreateQuery(QueryHints hints, @Nullable Predicate... predicate)` (which perhaps you've gleaned) since this is where Spring Data JPA calls Querydsl to fashion any/all queries based on predicates. This method, whatever it is, would also need access to the `EntityPath<T> path` to simply have the same information it currently uses.

As Mark said, hooking in your own `QuerydslJpaPredicateExecutor` indeed requires hooking into the machinery of Spring Data JPA's fragment registration process.

Based on your subsequent feedback, I'm not sure if there is any suitable alternative to registering a custom fragment. And if that is true, maybe we need a more user-friendly SPI to register custom fragments. That way you don't have to get into the guts of Spring Data JPA's machinery. I need to inspect the details to see how easy using either a market interface or an annotation would be.

```java
public class MyCustomQuerydslJpaExectutorFragment implements SpringDataFragment {}
```

or

```java
@SpringDataFragment
public class MyCustomQueryJpaExectutorFragment {}
```

**Comment by gregturn** [comment]
This much at least you can do by hand...

```java
	interface QueryDslSampleRepository extends JpaRepository<User, Integer>, QuerydslPredicateExecutor<User> {

		User findByFirstname(String name);

	}

	class CustomQuerydslJpaPredicateExecutor<T> extends QuerydslJpaPredicateExecutor<T> {

		public CustomQuerydslJpaPredicateExecutor(JpaEntityInformation<T, ?> entityInformation, EntityManager entityManager,
				EntityPathResolver resolver, CrudMethodMetadata metadata) {
			super(entityInformation, entityManager, resolver, metadata);
		}

	}

	class CustomFragmentJpaRepositoryFactory extends JpaRepositoryFactory {

		public CustomFragmentJpaRepositoryFactory(EntityManager entityManager) {
			super(entityManager);
		}

		@Override
		protected RepositoryFragments getRepositoryFragments(RepositoryMetadata metadata, EntityManager entityManager,
				EntityPathResolver resolver, CrudMethodMetadata crudMethodMetadata) {

			JpaEntityInformation<?, Serializable> entityInformation = getEntityInformation(metadata.getDomainType());

			RepositoryFragment customFragment = RepositoryFragment.implemented(new CustomQuerydslJpaPredicateExecutor<>(
					getEntityInformation(metadata.getDomainType()), entityManager, resolver, crudMethodMetadata));

			return RepositoryFragments.of(customFragment);
		}
	}

	class CustomFragmentJpaRepositoryFactoryBean<T extends Repository<S, ID>, S, ID>
			extends JpaRepositoryFactoryBean<T, S, ID> {

		public CustomFragmentJpaRepositoryFactoryBean(Class<? extends T> repositoryInterface) {
			super(repositoryInterface);
		}

		@Override
		protected RepositoryFactorySupport createRepositoryFactory(EntityManager entityManager) {
			return new CustomFragmentJpaRepositoryFactory(entityManager);
		}
	}

	@Configuration
	@ImportResource("classpath:infrastructure.xml")
	@EnableJpaRepositories(repositoryFactoryBeanClass = CustomFragmentJpaRepositoryFactoryBean.class)
	static class Config {}
```

That may be a bit hefty, but it DOES gives you the ability to plugin in your own implementation of `QuerydslPredicateExecutor`, giving you control over how Querydsl works for you.

I'm still tinkering with the ability to plugin in custom fragments, but at least this is something you can do today.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by mmm8955405** [comment]
How to configure spring jpa when the Q class of querydsl and the entity class of jpa are not in the same package
