### ISSUE TITLE
Support for DTO projections in derived query methods

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-data-jpa#2363]
Currently, projecting a query result into a DTO requires the query to be defined explicitly so that the constructor expression to assemble the instances can be declared explicitly. The projection execution of derived query methods currently only supports interface-based projections by reading the required input properties into a JPA `Tuple`.

It would be nice if we could create the query to use a constructor expression without that explicit declaration.

Related tickets:

* #487 
* #2078

**Comment by nidhikaushal** [comment]
@odrotbohm 
I was trying to use projection with specification, but I am getting the error: 
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.entity.ParticipationEntity] to type [com.entity.TenantOnly]

projection interface

public interface TenantOnly {
    String getTenantId();
}

@Data
@Entity
@Table(name = "participation", schema = "public")
public class ParticipationEntity {

    @Id
    @Column(name = "id")
    private Long id;

    @Column(name = "programId")
    private String programId;

    @Column(name = "tenantId")
    private String tenantId;

}

Spring Data repository
public interface ParticipationSpringDataRepository extends JpaRepository<ParticipationEntity, Long>, JpaSpecificationExecutor<ParticipationEntity> {
    List<TenantOnly> findAll(Specification specification);
}


    public List<String> getParticipatingTenants(List<String> tenantIds,  List<String> programIds, OffsetDateTime processedDate){
        List<TenantOnly> tenantOnlies = participationSpringDataRepository.findAll(
                Specification.where(tenantIdIn(tenantIds))
                        .and(programId(programIds)));

        return tenantOnlies.stream().map(tenantOnly -> tenantOnly.getTenantId()).toList();
    }

    private Specification<ParticipationEntity> tenantIdIn(List<String> tenantIds){
        return (root,  query, criteriaBuilder) -> {
            if(tenantIds == null || tenantIds.isEmpty()){
                return criteriaBuilder.conjunction();
            }
            return criteriaBuilder.in(root.get(ParticipationEntity_.TENANT_ID)).value(tenantIds);
        };
    }

**Comment by nidhikaushal** [comment]
@odrotbohm 
I have raised a bug here: https://github.com/spring-projects/spring-data-jpa/issues/2959
