### ISSUE TITLE
@Transactional @SpringBootTest does not execute several entity listener methods

### ISSUE THREAD

**Issue by hughwphamill** [spring-projects/spring-data-jpa#2473]
Spring Boot v2.6.4

`@Transactional` tests are useful to rollback any test data created during tests, however when a spring boot test is annotated with `@Transactional` the following entity listener methods are not executed:

* `@PostPersist`
* `@PostLoad`
* `@PreUpdate`
* `@PostUpdate`

Example project with unit tests demonstrating the issue here:

https://github.com/hughwphamill/transaction-test-entity-issue

**Comment by schauder** [comment]
The problem seems to be a misunderstanding of how JPA works. JPAs `persist` doesn't persist anything but merely registers entities to be eventually persisted. And for Spring Data JPAs `save` the same is true because it just delegates to JPA.
But the events `PostPersist` `PreUpdate` and `PostUpdate` only get triggered when the actual writing to the database happens. This would normally happen during a commit, but in the test it doesn't because the commit never happens.

As for the `PostLoad`: JPA caches entities in the first level cache. So when you "load" an entity you just "persisted" within the same transaction, it will not dehydrate the entity from the database but return the one from the cache. Therefore no entity really gets loaded and no events get triggered.

**Comment by hughwphamill** [comment]
Should this be an issue for spring framework or spring test then?

The outcome is the same, code that relies on entity listeners cannot be tested in a transactional test.

**Comment by schauder** [comment]
It is not an issue. It is just the way JPA works.
