### ISSUE TITLE
No property customize found for type with QuerydslBinderCustomizer in Kotlin

### ISSUE THREAD

**Issue by zhengchalei** [spring-projects/spring-data-jpa#2576]
like this https://stackoverflow.com/questions/63875195/no-property-customize-found-for-type-with-querydslbindercustomizer-in-kotlin

It can be solved with  `-Xjvm-default=enable` and  `@JvmDefault` 

Hope to be compatible with kotlin in a better way

**Comment by mp911de** [comment]
There's not much we can do as Kotlin's defaulting mechanism expects the implementor to handle the defaulting. The compiled interface defines an interface method. Spring Data attempts to derive a query from the method declaration as the method isn't implemented by a base repository. Since there's no `customize` property on the domain model, query derivation fails.
