### ISSUE TITLE
mysqlx - X DevAPI Implementation,

### ISSUE THREAD

**Issue by Exnadella** [spring-projects/spring-data-jpa#2577]
We like to have a sample application created for saving documents on MySQL 8.0.29 which used X Protocol to connect via Xdevapi on port 33060 in the form of JSON Documents (Collections).  We also need a connection pooling functionality to be able to work with the Atomikos transaction manager.  Any help with a sample implementation in Spring-Boot will be helpful.  

We are unable to define a Bean to connect via the Xdevapi data source.  We can create beans on Spring-Data-JPA, but we are unable to create a connection pooling.

Documentation on XDevapi is available below.
https://dev.mysql.com/doc/x-devapi-userguide/en/devapi-users-working-with-collections.html
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-installing-maven.html
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-schema-validation.html
https://stackoverflow.com/questions/58322205/how-can-i-use-spring-boot-data-jpa-with-mysql8-collections-will-spring-boot-dat

**Comment by schauder** [comment]
I'm not familiar with the xdevapi. But it seems to be an alternative to JDBC.

You would either need a JDBC driver build on the x-devapi, which would probably negate the purpose of the x-devapi.
Or you'd need a JPA implementation that can use the x-devapi. 

I couldn't find any of those, so it seems you can't use JPA with it and therefore also not Spring Data JPA.

Or am I misunderstanding something?

**Comment by Exnadella** [comment]
Hi Schauder,

Thanks for the quick response.  JDBC is for Relational Tables, X DevAPI is used for storing JSON documents.  MySQL has launched a new InnoDB Database (In-Memory Database) which has implemented X Protocol and listens on port 33060 which in turn uses com.google.protobuf as a dependency.

The data is stored in the form of Key-Value and stored as JSON document which MySQL has named as collections, we have an implementation of the same in Reactive relational database connectivity by R2dbc https://github.com/linux-china/r2dbc-mysqlx
and is supported by Vmware and email to contact is r2dbc@vmware.com and the website is https://r2dbc.io/

The below dependencies are used to connect to the MySQL DB.
<dependency>
  <groupId>mysql</groupId>
  <artifactId>mysql-connector-java</artifactId>
  <version>8.0.29</version>
</dependency>
<dependency>
   <groupId>com.google.protobuf</groupId>
   <artifactId>protobuf-java</artifactId>
   <version>3.19.4</version>
</dependency>

We use the below program to establish a connection 
Session mySession = new SessionFactory()
                .getSession("mysqlx://localhost:33060/repositoryname?user=username&password=dbpassword");

the below imports are used in saving the data 
import com.mysql.cj.xdevapi.Collection;
import com.mysql.cj.xdevapi.DbDoc;
import com.mysql.cj.xdevapi.DocResult;
import com.mysql.cj.xdevapi.JsonString;
import com.mysql.cj.xdevapi.Schema;
import com.mysql.cj.xdevapi.Session;
import com.mysql.cj.xdevapi.SessionFactory;

It should be possible to use Spring Boot JPA or Spring Data JPA to able to develop a sample application that has connection pooling to be able to use with Transaction Manager.

**Comment by Exnadella** [comment]
The above functionality was already requested in Feb 2020.  It is suggested to raise this in Jira https://jira.spring.io/projects/ but not added.
https://github.com/spring-projects/spring-framework/issues/24545

**Comment by schauder** [comment]
As you pointed out someone provided a R2DBC driver for XDevAPI which is all you need to enable Spring Data R2DBC (and maybe a dialect). Note that that driver is not maintained by VMware or the Spring team.

Similarly we would need a JDBC driver in order to utilise existing JPA implementations or a special JPA implementation in order to support it in Spring Data JPA. Both will not be provided nor maintained by the Spring Data team.

The request in https://github.com/spring-projects/spring-framework/issues/24545 is a slightly different one. It asks for a new Spring Data module for XDevAPI. Since you already pointed out that Spring Data R2DBC does offer support for it already I don't think a separate module is needed. And even if it would be desirable the team is not able to support another module.

As for connection pooling: This should be provided by those responsible for the protocol, which would be the MySql folks I guess.

As for transaction management. AFAIK you'd need a [`PlatformTransactionManager`](https://github.com/spring-projects/spring-framework/blob/0783f0762d72df70572aaceeee099c3ec4b7e019/spring-tx/src/main/java/org/springframework/transaction/PlatformTransactionManager.java) implementation. If X DevAPI offers the required functionality it shouldn't be too difficult to implement. You may ask for an implementation over at https://github.com/spring-projects/spring-framework/issues but I suspect it is easier to just create an implementation on your own.
