### ISSUE TITLE
JSqlParserQueryEnhancer errors with INSERT statements

### ISSUE THREAD

**Issue by stulscott** [spring-projects/spring-data-jpa#2593]
When starting a Spring Boot application with >= 2.7.0 the application fails to start if it has native INSERT queries defined in JpaRepositories. The error is:

java.lang.ClassCastException: class net.sf.jsqlparser.statement.insert.Insert cannot be cast to class net.sf.jsqlparser.statement.select.Select

For example, any JpaRepository with the following will error and prevent the application from starting:

```
    @Modifying
    @Query(value = "INSERT INTO FOO(A) VALUES('A')", nativeQuery = true)
    void insertFoo();
```

`detectParsedType()` appears to neglect the Insert statement type:

```
			Statement statement = CCJSqlParserUtil.parse(this.query.getQueryString());

			if (statement instanceof Update) {
				return ParsedType.UPDATE;
			} else if (statement instanceof Delete) {
				return ParsedType.DELETE;
			} else if (statement instanceof Select) {
				return ParsedType.SELECT;
			} else {
				return ParsedType.SELECT;
			}
```

**Comment by DiegoKrupitza** [comment]
Yeah you are totally right. When working a344a76959e0b356ac15e81d578f87e860566232 I did not though about `INSERT` statements 🤦🏽‍♂️. Working on a PR that should fix that issue

**Comment by DaDom** [comment]
Hey @DiegoKrupitza and @gregturn !
Thanks a lot for working on this fix!
Will it be backported to 2.7.x, or only be available in version 3?

**Comment by tofdragon** [comment]
2.7.x ?

**Comment by DiegoKrupitza** [comment]
Hey @DaDom & @tofdragon. Unfortunately I don't know if this will be backported to 2.7.x, since this is decided(?)/managed by the members of the spring-data-jpa team.
Since you already pinged @gregturn I think once he sees this and finds time to do it I see no reason why this should not happen. 

There is currently a lot happening with QueryEnhancer so I think the next big change (https://github.com/spring-projects/spring-data-jpa/pull/2639) will not be backported, so in the future it may be feasible to "upgrade". But this is just my personal opinion maybe the leads of this project have other plans.  

Hope this somehow helps :)

**Comment by gregturn** [comment]
Backported to `2.7.x`.
