### ISSUE TITLE
query plan cache of Specification

### ISSUE THREAD

**Issue by SnowsonZ** [spring-projects/spring-data-jpa#2605]
When using Specification, it is found that the plan cache occupies a large amount of memory, and the following is the memory occupancy dump

![image](https://user-images.githubusercontent.com/12555482/180941777-3e698ea0-a39c-4646-87ef-16f6a096e9df.png)

When the same query does not use Specification, the memory usage is dumped

![image](https://user-images.githubusercontent.com/12555482/180937532-3f5f8582-7a6a-47f2-b63a-d186b99f77ef.png)

JPA config

![image](https://user-images.githubusercontent.com/12555482/180937626-41dbd087-27cc-48b7-8a62-4b96b69e13bc.png)

btw，When using Specification, when the query parameter is a number, the placeholder is not used but the actual value

HQL:

![image](https://user-images.githubusercontent.com/12555482/180941139-93536a65-a5be-4f12-8634-3651bb84ce41.png)

SQL:

![image](https://user-images.githubusercontent.com/12555482/180939873-ce9e4f9b-27ec-4ed0-94d4-802a7e7fb799.png)

Code:

![image](https://user-images.githubusercontent.com/12555482/180942464-189e21cb-c406-48ac-b1f3-21efc7d9b7f2.png)

**Comment by schauder** [comment]
This is out of scope for Spring Data JPA. We just combine the `Predicate` provided by the `Specification` with a base query.

All the rest like generating SQL, caching of statements and so on is done by the JPA implementation.

Since you are using Hibernate, this article by Vlad Mihalcea might be helpful regarding usage of parameters vs literals.
https://vladmihalcea.com/how-does-hibernate-handle-jpa-criteria-api-literals/

In order to be more vendor independent you may use `CriteriaBuilder.parameter()`
