### ISSUE TITLE
Excuse me, have I found a bug?

### ISSUE THREAD

**Issue by RavenCri** [spring-projects/spring-data-jpa#2634]
For the following code, when I use spring transaction annotation
```
@Transactional()
@Rollback(value = false)
@Test
public  void test(){
    Person person = new Person();
    person.setName("小王");
    personRepository.save(person);
    person.setName("小李");
}
```
It can be seen from the log why there is an update SQL statement? I did not save again after the last setName
![image](https://user-images.githubusercontent.com/39519250/190403418-826d93e4-b4d1-42de-b667-8cf6b43bdf3d.png)
However, when I do not use the transaction annotation,The above update SQL log does not appear.
![image](https://user-images.githubusercontent.com/39519250/190403982-c3cf710d-47b3-4ee7-9c07-c0c863622087.png)
Can you tell me the answer?

**Comment by schauder** [comment]
This is normal JPA behaviour. Modified managed entities are saved at the end a transaction.
I recommend reading up on the JPA entity Lifecycle, dirty checking, flushing and first level cache.

This issue tracker is for bug reports and feature/improvement requests. 
This question is more of a usage questions. Those should be asked at Stackoverflow and be tagged with `spring-data-jpa` or in this case actually `jpa`.
By using Stackoverflow, the community can assist and the questions and their answers can more easily be found using the search engine of your choice.

Finally please post code and logs as text instead of images. Images can be hard to read, can't be used in answer and don't get indexed.

**Comment by RavenCri** [comment]
thanks!
