### ISSUE TITLE
Inconsistent behavior with @Query when using ENUMs

### ISSUE THREAD

**Issue by danielnsilva** [spring-projects/spring-data-jpa#2652]
I have a @Query to perform a search in multiple fields. The ```gender``` field is an ```enum```, which is stored as string in DB.

```java
@Query(
    "select p FROM Person p" +
    " where p.gender like %:searchString%" +
    " or p.name like %:searchString%"
)
List<Person> search(String searchString);
```

Invoking ```search('FEMALE')``` ends up with:
```console
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value [%FEMALE%] did not match expected type [com.example.demo.EGender (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [%FEMALE%] did not match expected type [com.example.demo.EGender (n/a)]
```

However, when changing ```gender``` field position in WHERE clause, the query runs well.

```java
@Query(
    "select p FROM Person p" +
    " where p.name like %:searchString%" +
    " or p.gender like %:searchString%"
)
List<Person> search(String searchString);
```

Not sure if I missing something here, but it seems a bug to me. I made a reproducible example available in [this repo](https://github.com/danielnsilva/spring-jpa-query-enum).

**Comment by hariohmprasath** [comment]
Hi @danielnsilva,
Based on my understanding `parameterCache` gets built based on the name of the placeholder variable (`searchString`) in the query, so in case of the second SQL, `searchString` is resolved as `StringType` and the same type gets reused when mapping enum attribute (`or p.gender like %:searchString%`), hence the code executes without any error.

```
@Query(
    "select p FROM Person p" +
    " where p.name like %:searchString%" +
    " or p.gender like %:searchString%"
)
List<Person> search(String searchString);
```

But for the first query, the `searchString` will get mapped to CustomType based on `Enum` and since passed in value `searchString` is not of type `Enum` we get an exception when running the query:

```sql
@Query(
    "select p FROM Person p" +
    " where p.gender like %:searchString%" +
    " or p.name like %:searchString%"
)
```

Also by looking at the query seems like you are performing a `like` operation on a `enum` attribute this may not be supported. So if you rewrite your query like below everything should work as expected:

```
@Query(
    "select p FROM Person p" +
    " where p.gender = :searchString" +
    " or p.name like '%:searchString%'"
)
List<Person> search(EGender searchString);
```

BTW I am not an expect in spring-data-jpa code base just trying to help :)

**Comment by danielnsilva** [comment]
Thank you, @hariohmprasath.

But one question remains, why am I getting expected results on the second query if a LIKE operation on a ENUM is not supported?

If I call the endpoint ```/search/FEMALE```, the API returns the expected JSON containing the only Person with FEMALE gender.

```java
@GetMapping(value="/search/{searchString}")
public ResponseEntity<List<Person>> searchPersons(@PathVariable("searchString") String searchString) {
    List<Person> results = repo.search(searchString);
    return new ResponseEntity<List<Person>>(results, HttpStatus.OK);
}
```
```java
@Query(
     "select p FROM Person p" +
    " where p.name like %:searchString%" +
     " or p.gender like %:searchString%"
)
List<Person> search(String searchString);
```
```sql
INSERT INTO `person` VALUES
    (1,'FEMALE','Reya Cooley'),
    (2,'MALE','Caio Talley'),
    (3,'MALE','Gianluca Tierney');
```

Output:
```json
[
  {
    "id": 1,
    "name": "Reya Cooley",
    "gender": "FEMALE"
  }
]
```

**Comment by danielnsilva** [comment]
I've upgraded to Spring Boot 3.0.2 (with Spring Data JPA 3.0.1) and the inconsistent behavior is not observed anymore. As explained by @hariohmprasath, the `like` operation on an `enum` attribute is not supported. So, now both query examples fail. The examples were originally made with Spring Data JPA 2.7.3.

Thanks again to @hariohmprasath for helping to clarify this!
