### ISSUE TITLE
support dynamic sql like mybatis with xml

### ISSUE THREAD

**Issue by albert-get** [spring-projects/spring-data-jpa#2724]
when i use jpa,api is very easy to use.but sometimes,i have to create sql string by self,because of @query is  not dynamic sql that is not suitable.mybatis can create dynamic sql in xml,it is really easy to understand by everyone,and it is a good standard.jpa will support this?

**Comment by schauder** [comment]
JPA itself has the Criteria API for creating dynamic queries. You may use it in custom method implementations or via Specifications in Spring Data JPA.

There is also integration with Querydsl which serves a similar purpose but is nicer to use than the Criteria API.

An integration of Spring Data JPA with Mybatis is not planned.
We can't speak for JPA but I consider it highly unlikely that a standard will offer integration with a proprietary library.

Since you are asking on the Spring Data JPA issue tracker about JPA, this [Stackoverflow about their relation](https://stackoverflow.com/a/23863416/66686) might be of interest for you.

**Comment by holmofy** [comment]
Recently, I provide a criteria extension, which can implement the feature of dynamic sql.
https://github.com/holmofy/spring-data-criteria

It is based on the **Criteria API** specification of JPA.

```java
default Page<User> searchByQuery(UserQuery query, Pageable pageable) {
    return findAll(Criteria.from(eq(User_.province, query.province))
                    .and(eq(User_.city, query.city))
                    .and(like(User_.area, query.area))
                    .and(like(User_.name, query.nick))
                    .and(between(User_.created, query.createFrom, query.createTo))
            , pageable);
}
```
