### ISSUE TITLE
springboot 3.0.0 + db2 error after migrating from springboot 2.7.0

### ISSUE THREAD

**Issue by fseznec** [spring-projects/spring-data-jpa#2732]
### Steps to reproduce :
 - create a springboot 2.7.0 project with a IBM db2 datasource and a simple JpaRepository
 - create a junit test just checking that the findAll() method does not throw
 - run the junit test, test is OK
 - migrate to springboot 3.0.0
 - run the junit test, test fails with :
```
[...] org.springframework.dao.InvalidDataAccessResourceUsageException: JDBC exception executing SQL [select * from (select e1_0.empno c0,row_number() over() rn from employee e1_0) r_0_ where  order by r_0_.rn]; SQL [n/a]
    at nc.bci.SpringbootDb2ApplicationTests.testFindAll(SpringbootDb2ApplicationTests.java:16)
```

### Minimal sample project
I have isolated the issue and created a minimalist project to reproduce (attached).
If you have git, maven and docker (to easily setup a DB2 database) it should be easy to reproduce.
I have carefully written a README.md.
[springboot3-db2-application.zip](https://github.com/spring-projects/spring-data-jpa/files/10233972/springboot3-db2-application.zip)

**Comment by schauder** [comment]
I can not easily reproduce this. There are no DB2 images compatible with my machine.

But if this is indeed DB2 specific, it is almost certainly a Hibernate issue, because all the mapping to databases is done by Hibernate.
Spring Data JPA is only using the JPA API which should be database independent.

The next step would be to recreate the issue using just an `EntityManager`, create a criteria query loading all entities and executing it and also trying both tests against at least a second database like H2.

If the same happens with all databases but only when using the repository abstractions, I'll take another look.
Otherwise you should raise this with the Hibernate team.

**Comment by robotmonkeylives** [comment]
Encountering the same problem. 

- When running as a criteria query the same issue presents. 
- When running against a H2 database the SQL is formed correctly and runs without issue

**Comment by fseznec** [comment]
> If the same happens with all databases but only when using the repository abstractions, I'll take another look. Otherwise you should raise this with the Hibernate team.

I raised this issue with the hibernate team : https://hibernate.atlassian.net/browse/HHH-15890
