### ISSUE TITLE
Re-introduce support for Hibernate 5

### ISSUE THREAD

**Issue by belovaf** [spring-projects/spring-data-jpa#2765]
We mirgated our projects to spring boot 3 but we noticed, that hibernate 6 is very unstable.
We submited several crtical issues:
1) Broken custom types: https://hibernate.atlassian.net/browse/HHH-15953
2) Broken lazy loading:
https://hibernate.atlassian.net/browse/HHH-16043
3) Broken user types with inheritence

I add locally `HIBERNATE5` to `PersistenceProvider`,
add old Hibernate5JpaParametersParameterAccessor,
replace hibernate-core:6.1.6 with hibernate-core-jakarta:5.6.14
and everything is working fine.

I think this option will be very helpful for others.

**Comment by odrotbohm** [comment]
It's not that simple, unfortunately. Spring Data JPA doesn't compile against Hibernate 5 anymore, and the legacy implementation of `HibernateJpaParametersParameterAccessor` used API not available in Hibernate 6. In other words, there's no way for us to compile against one version of Hibernate and support the other.

Generally speaking, we try to avoid having to maintain support for different major versions of a persistence provider, as that causes significant effort in Framework, Spring Data JPA and downstream Spring Boot. Especially, as these generations previously have shown to diverge significantly, and we cannot quit the support for a Hibernate generation in the mid of a release generation of our own if the differences become unmaintainable.

I would recommend making your voice heard in the [Hibernate issue tracker](https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues). I guess you might already have, but getting these bugs fixed by the Hibernate team is the only reasonable way forward. For now, we recommend staying on Boot 2.7 should you run into Hibernate related issues during the upgrade. Rest assured, we keep monitoring the situation and consider all options available.
