### ISSUE TITLE
SpEL support for @Procedure

### ISSUE THREAD

**Issue by Tomschi** [spring-projects/spring-data-jpa#2771]
I want to externalize the PL/SQL package prefix of the procedure name in the `@Procedure` annotation.

E.g. `@Procedure(procedureName = "${database.plsql.package-prefix}.getAll", outputParameterName = "pRc", refCursor = true)`

Is it possible to add SpEL support?

**Comment by schauder** [comment]
Related: https://github.com/spring-projects/spring-data-relational/issues/1325#issuecomment-1269648942

**Comment by mp911de** [comment]
Thanks for reaching out. We've spiked on the issue and it turns out to be overly complex when considering all parts being involved in procedure metadata resolution. Our abstractions do not capture context required for stored procedure metadata as we assume that during query initialization the stored procedure name is static.

Introducing a dynamic name that can potentially change for each invocation, we need to capture all sorts of state and pass it on. Given the complexity vs. its benefits we rather abstain from introducing Value Expression support (that is SpEL and Property Placeholder resolution).
