### ISSUE TITLE
CriteriaBuilder function don't add the function in the query

### ISSUE THREAD

**Issue by marccollin** [spring-projects/spring-data-jpa#2799]
I use spring boot 3 and spring data jpa

I try to use contains of oracle.

I used criteriaBuilder function to add it.

     public Page<User> genericAdvancedSearch(UserSearch search, Pageable page) {

        Specification<User> specification = (Root<User> root, CriteriaQuery<?> cq, CriteriaBuilder cb) -> {

           Predicate p  = cb.disjunction();
           p.getExpressions().add(cb.function("contains", Boolean.class, root.get("firstname"), cb.literal(search.firstname())));

           return p;
        };
       return findAll(specification, page);
   }

Actually the query generated give

```
select
  u.firstname,
  u.lastname,
  u.datebirth
from user u
where 1!=1
```

I should get

```
select
  u.firstname,
  u.lastname,
  u.datebirth
from user u
where contains (firstname , ?, 1) > 0
```

I get the same result if I use directly criteria

```
CriteriaBuilder cb = entityManager.getCriteriaBuilder();
CriteriaQuery<User> cq = cb.createQuery(User.class);
Root<User> rootUser = cq.from(User.class);

Predicate p  = cb.disjunction();
p.getExpressions().add(cb.function("contains", Boolean.class, rootUser.get("firstname"), cb.literal(firstname)));
    cq.where(p);

List<User> queryResult=entityManager.createQuery(cq).getResultList();
```

with this code
```
CriteriaBuilder cb = entityManager.getCriteriaBuilder();
CriteriaQuery<User> cq = cb.createQuery(User.class);
Root<User> rootUser = cq.from(User.class);
String nom= "jean";
Expression<Boolean> contains = cb.function("CONTAINS", Boolean.class, rootUser.get("firstname"), cb.literal(firstname));
cq.where(contains);
```

I get

select
  u.firstname,
  u.lastname,
  u.datebirth
from user u
where contains (u.firstname , ?, 1) 

so > 0 is missing

**Comment by schauder** [comment]
This issue tracker is for bug reports and feature/improvement requests. 
This question is more of a usage questions. Those should be asked at Stackoverflow and be tagged with `spring-data-jpa` or actually `jpa` in this case since it is not really about Spring Data JPA either.
By using Stackoverflow, the community can assist and the questions and their answers can more easily be found using the search engine of your choice.

But since you are already here:

You are using `Predicate.getExpressions().add` to add an expression to an existing predicate. But the [JavaDoc of `Predicate.getExpressions()` explicitly states] (https://docs.oracle.com/javaee/7/api/javax/persistence/criteria/Predicate.html#getExpressions--) (emphasis is mine
>  Return the top-level conjuncts or disjuncts of the predicate. Returns empty list if there are no top-level conjuncts or disjuncts of the predicate. **Modifications to the list do not affect the query.**

Use [`CriteriaBuilder.and(Predicate ... predicates)`](https://docs.oracle.com/javaee/7/api/javax/persistence/criteria/CriteriaBuilder.html#and-javax.persistence.criteria.Predicate...-) instead.
