### ISSUE TITLE
NPE on all Native Queries

### ISSUE THREAD

**Issue by zromano** [spring-projects/spring-data-jpa#2826]
With the latest version of SpringBoot + Spring Data JPA, we get NPEs on all native queries.

This happens because `variable` on like 620 of `QueryUtils.java` is `null`. Looks like this is fixed in the code but not released.

Any ETA on when this will be out? It completely breaks our service right now.

Here is a link to the commit that fixes this:
https://github.com/spring-projects/spring-data-jpa/commits/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query

**Comment by mschout** [comment]
We are also affected, going back to 3.0.2 for now.

**Comment by gregturn** [comment]
Just to be clear, since you said "latest version of Spring Boot", I didn't know if you were using Spring Boot `3.0.3` or `3.1.0-M1`. The information above is for Spring Boot `3.0.x`. If you're on Spring Boot `3.1.x`, then you'll want to use `2023.0.0-SNAPHOT`. `2023.0.0-M3` is also coming March 17th.

**Comment by mschout** [comment]
Spring Boot `3.0.3` is affected (just to clarify)

**Comment by zromano** [comment]
cc @gregturn

**Comment by mschout** [comment]
This fix is in 3.0.4, which is now releaseed FYI
