### ISSUE TITLE
Regarding SimpleJPARepository @Transactional(readOnly=true) methods no-rollback defaults

### ISSUE THREAD

**Issue by nightswimmings** [spring-projects/spring-data-jpa#2830]
By reading the following article https://dev.to/kirekov/spring-never-rollback-readonly-transactions-28kb I was wondering if there is any rationale by Spring Data JPA team to not follow this design by default in SimpleJPARepository, and if so, maybe it could be assessable to implement it like that. 

Looks like its arguably the best option, but I am wondering if it might be a counterargument.

**Comment by mp911de** [comment]
Updating transactional attributes via a nested `@Transactional` within the same propagation bounds violates consistency guarantees of a transaction and is actually a bug already in the calling code. Code for reuse should be designed accordingly so that it doesn't reside within a `@Transactional` method but rather in a delegate that can be reused.

The read-only flag is rather a hint to participants of a transaction to apply certain optimizations. For instance, Hibernate can disable dirty tracking within a readonly transaction.

Let me know whether this helps.

**Comment by odrotbohm** [comment]
I'm not sure what I understand what problem the blog post is trying to fix. It's constructing a problem by deciding to throw exceptions from a method that only does some business verification. Using exceptions for control flow is [an anti-pattern](https://softwareengineering.stackexchange.com/questions/189222/are-exceptions-as-control-flow-considered-a-serious-antipattern-if-so-why).

Runtime exceptions mark transactions for rollback. Always have, always will. If you don't want to do that, don't throw exceptions, but rather return a custom type that captures the verification result so that clients can act on. Designing a method to throw exceptions and then complaining about having to add glue code to catch these exceptions feels rather weird to me.

**Comment by nightswimmings** [comment]
Yes, I don't know where the hell was my mind the day I opened the issue, but I was referring to JPASimpleRepository @Transactional(readonly=true) methods setting noRollbackFor = Exception.class.

**Comment by mp911de** [comment]
Either commit or rollback needs to happen to clean up the transaction. With [some databases](https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L4539) not considering the read-only flag at all, it is probably a question over whether something should be written into your database transaction log.

I'd argue that there's almost no difference.

**Comment by odrotbohm** [comment]
> I am not sure any of both answers actually apply on what I had on mind although I appreciate them!. The point here is whether it makes sense to rollback reaodnly transactions upon exception

I apologize for misunderstanding, but you referred to a blog post and asked why we don't follow this design by default. I answered that what is suggested is a self-inflicted problem and there actually is really nothing to follow.

Mark actually summarized it pretty well. I'd only add that rolling back on runtime exceptions has been a pattern established for almost two decades, aligned with practices in JavaEE / JakarataEE. There's no way this is going to change, as it would break millions of applications out there. Plus, again, the rollback only causes problems if you use exceptions for control flow, which, as outlined above, is wrong in the first place.

**Comment by gregturn** [comment]
Based on comments from @odrotbohm and @mp911de, I am closing this issue as the flow we currently use is best aligned with standard practices regarding transaction management.
