### ISSUE TITLE
spring.jpa.properties.hibernate.jdbc.fetch_size not working Spring 3.X and Oracle

### ISSUE THREAD

**Issue by justinsmyth** [spring-projects/spring-data-jpa#2835]
When running a query with spring.jpa.properties.hibernate.jdbc.fetch_size increased in spring-data-jpa 2.7.3 there is a performance improvement with Oracle but with 3.x or higher this parameter does not appear to do anything.

**Comment by schauder** [comment]
Same report on Stackoverflow https://stackoverflow.com/questions/75608212/spring-jpa-properties-hibernate-jdbc-fetch-size-not-working-for-spring-framework

**Comment by schauder** [comment]
This is probably not a Spring Data JPA issue, because we don't really touch this value.
Spring Boot only passes this stuff on, so a bug there is unlikely as well.
Most likely candidates are Hibernate or maybe even the Oracle JDBC driver.

Please provide a reproducer, including the database using Testcontainers, demonstrating that this works with Hibernate directly but doesn't work with Spring Data JPA and Spring Boot.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ckoutsouridis** [comment]
another way to make `spring.jpa.properties.hibernate.jdbc.fetch_size` to be respected is using streams. for example the bellow does set the statement.fetchSize() of the driver

```
    @Query("select o from MyDomainObject o")
    Stream<MyDomainObject> findEntities();

````

this value is set by hibernates `StatementPreparerImpl`. and only in method 
```
public PreparedStatement prepareQueryStatement(
			String sql,
			final boolean isCallable,
			final ScrollMode scrollMode)
```

with spring boot 2.7.x jpa repository methods ended up on that method, but with spring boot 3.x the above is invoked only for stream methods.

i do not know much details on this.. but it might be a spring-data-jpa issue
