### ISSUE TITLE
createdAt field annotated with @CreationDate gets updated when an entity is modified. [using spring boot 3.0.4]

### ISSUE THREAD

**Issue by isatishp** [spring-projects/spring-data-jpa#2844]
When an entity is modified, we see that created time gets updated. This happens with newly created entity, for older entities it works fine. 

Steps to reproduce:

1. Create an entity which has fields annotated with @CreatedDate @ModifiedDate and @EntityListeners(AuditingEntityListener.class)
2. Save the entity using JPA Repository class
3. Update the entity 
4. And, you see updated entity has creationDate from the future

**Comment by schauder** [comment]
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by isatishp** [comment]
Hi I tried an example using embedded DB and I could not reproduce this issue with in memory DB. However, the moment I switched to Postgres which is also the db we use, I could reproduce the issue.. Unfortunately I do not know how to do an implementation with Test Containers.. But I have a working example here that reproduces the issue. 

https://github.com/isatishp/student-crud

**Comment by isatishp** [comment]
![image](https://user-images.githubusercontent.com/30146971/223535407-94feab43-b9c7-48f5-9022-41ae52143e29.png)
Also, the modified timestamp is saved in local timezone which was not the case with sprint boot v2.7.9. I tried 3.0.4 with postgres version used in v2.7.9 which is postgres:42.3.8 and is still reproducible.

**Comment by schauder** [comment]
I tried to create a reproducer out of your repository but failed.

I created a PR which introduces a test using Testcontainers and removes the stuff that shouldn't have anything to do with the described problem.

Please modify that version of the reproducer to actually reproduce the original issue.

Please create separate issue for the second problem about the timezone issue.

**Comment by isatishp** [comment]
Thank you for updating the code to be working with TestContainers.

I have updated the tests so that multiple students are saved->fetched->updated and the issue was not reproducible. 
Then I just added column definition "timestamp" for CreatedAt and LastModifedAt and there I could reproduce the issue.

I tried the same with h2, because test containers take too long to execute tests, but could not reproduce it. 

please find the code here: https://github.com/isatishp/student-crud


I'll try having single student with column definition "timestamp" to see the results. Also, I have printed the students data before and after update so that we can compare their createdAt values.

Thanks!

**Comment by isatishp** [comment]
I tested with single student object and could still reproduce it..

**Comment by isatishp** [comment]
The exact same thing works with Spring boot 2.7.9. I have added a branch to the same repository for spring boot v2.7.9.. 

Thanks:)

**Comment by isatishp** [comment]
I tried debugging and following are my observations:
In Spring Boot 3: 
1. The createdAt and modifiedAt fields are supposed to get saved in UTC, but they get written to table in local time zone.
2. When you retrieve, the createdAt and modifiedAt fields have date with local time zone.
3. Updating entity results in updating the modifiedAt field with UTC time however, the createdAt which still has local time zone datetime is not updated. Therefore when updating the table, modifiedAt(UTC) is adjusted to local time zone, createdAt which is already at local timezone also gets adjusted again resulting in createdAt at save != createdAt at update..

Jsr310JpaConverters.InstantToTimestampConverter is not invoked. 
org.hibernate.type.descriptor.java.InstantJavaType wrap/unwrap is not invoked responsible for converting InstantToTimestamp and vice versa


In Spring Boot 2
The createdAt and modifiedAt both are saved to/ retrieved from the table in UTC format. Hence, we do not have the issue there.
org.hibernate.type.descriptor.java.InstantJavaDescriptor.java is invoked.

Hope this helps!! :)

Thanks :)

**Comment by isatishp** [comment]
I got the test case working with the property:

spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP

Seems that it is related to Hibernate 6 implementation.
https://stackoverflow.com/questions/75519276/spring-boot-3-hibernate-6-migration-timezone-mapping-issues.

Thank you for your time and effort!

**Comment by danvc** [comment]
I'm getting the same issue.

**Comment by nutmix** [comment]
I have the same issue.  Its necessary to read the existing data, and copy the created_at data to entities you are presisting so it doesnt update the created_at to when the row was updated.  @CreatedDate works like @UpdatedDate, if such a thing exists.  I looked at this example: https://docs.spring.io/spring-data/jpa/reference/auditing.html#auditing.basics Which requires quite a bit of code to get this to work. I didnt manage to get it to work, and have implemented a simple manual solution.  The other option is to use triggers, which will always give the correct results in the database, but because it happens after the record is inserted or updated, spring and your application will be missing this in the saved objects (requiring a re-read after saving).

**Comment by czyzby** [comment]
For anyone facing this issue or getting warnings about *"the property of the entity was modified, but it won't be updated because the property is immutable"*, in Spring Boot 4+ you can replace `@CreationTimestamp` with a `@Generated` annotation. By default, it assumes the value is generated on insert and not updatable. Hibernate will let the database generate it instead and won't validate it on subsequent saves. Just make sure that the column definition has a default at the database level, e.g. `default now()` in PostgreSQL.
