### ISSUE TITLE
Postgres stored procedures not executing

### ISSUE THREAD

**Issue by Jolymmiles** [spring-projects/spring-data-jpa#2903]
Get errors when start stored procedure

```
@Repository

public interface Repo extends CrudRepository<EntityClass, String> {
    @Procedure(procedureName = "sp_dis_hierarchy_sync_groups")
    void sync();
}

```
![image](https://user-images.githubusercontent.com/75259437/230096194-2b3fe121-a968-49cb-897f-46b0469198b8.png)
![image](https://user-images.githubusercontent.com/75259437/230096316-df6885b3-227f-457c-ab80-895aeb09917e.png)

**Comment by gregturn** [comment]
Looks like something fundamental has changed regarding stored procedures in Postgres 11+. Our current integration tests use Postgres 10, and run just fine. Back then, stored procedures were simply functions with a void return type.

Apparently, this has changed massively, and considering we simply later over JPA regarding stored procedure invocations, I'm trying to glean where the real issue is.

**Comment by gregturn** [comment]
@Jolymmiles What version of Postgres are you using?

**Comment by gregturn** [comment]
We know that this involves Postgres 11+.

**Comment by gregturn** [comment]
Because Postgres didn't have proper stored procedures in versions 10 and earlier, we had integration testing using that combined with that. However, with Postgres 11+, there is now proper support through JPA/Hibernate, etc. 

For stored procedures to work properly for you you can either:
* Upgraded your Postgres procedures from functions to procedures properly
* Instead of using `@Procedure`, switch to `@Query` and use select statement statements against the stored functions.

**Comment by gregturn** [comment]
Tests updated for `main`, `3.1.x`, and `3.0.x`. Checked out `2.7.x`, but Hibernate 5.x is still on Postgres 9, so not applicable.
