### ISSUE TITLE
CriteriaBuilder rounds value to 1 decimal place when using coalesce

### ISSUE THREAD

**Issue by dmck23** [spring-projects/spring-data-jpa#2912]
Since upgrading to Spring boot 3.0.5 we have had an issue with the code rounding the value of a sum calculation to 1 decimal place when used with coalesce.

`        cq.select(cb.coalesce(cb.sum(root.get("value")), BigDecimal.valueOf(0.0000000000)));
`

For the line above we expect a result of 2429.6030356778, but the query returns 2429.6

Without the coalesce it does not round the number to 1 decimal place as expected. It also works fine when i use a native query with JpaRepository

I've created a sample repo with test cases covering 3 scenarios: (https://github.com/dmck23/spring-data-criteria-coalesce/tree/spring-boot-3.0.5)

CriteriaRepositoryTest
1. getSummedValue - this just delects the sum value, and no rounding issue
2. getCoalesceSummedValue - a select with coalesce, this ends up rounding to 1 decimal place
3. getCoalesceRoundedSummedValue - this tries to use the round method but throws an AbstractMethodError 

UseJpaRepositoryTest
4. getSummedValue - uses native query with Coalesce and sum and has no rounding issues.

I've also got a branch with 2.7.10 code and it works as expected on that version. https://github.com/dmck23/spring-data-criteria-coalesce/tree/spring-boot-2.7.10

**Comment by schauder** [comment]
This sounds very much like a Hibernate issue, since all the JPA mapping is done by it.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` and a criteria query directly.
