### ISSUE TITLE
@Query(text block) java17

### ISSUE THREAD

**Issue by shuanshuan** [spring-projects/spring-data-jpa#2925]
Java : 17
spring boot: 3.0.4
spring-boot-starter-data-jpa

text block is not well support in query String.
if you write a JPQL 

  
```
   """
                select  c.username as username,
		c.mobile as mobile,
		tm.role as role,
		tm.clientId as clientId, 
		c.name as clientName,
		c.email as email,
		tm.createTime as createTime
                from TeamMember tm
                left join SpringUser c
                on tm.clientId = c.id
                where tm.teamId = :teamId
                and c.username like %:keywords%
                or c.mobile %:keywords%
                """
```
                  
the generate sql will ignore the LF, as `...tm.createTimeascreateTimefromTeamMembertmleftjoinSpringUsercontm.clientId=c.id...`

**Comment by gregturn** [comment]
For starters, using Spring Data JPA 3.1's query parser, I was able to spot that `c.mobile %:keywords%` is missing either a `LIKE` or an `=`. I don't know if that is the source of the issue. But I need to continue testing on Spring Data JPA 3.0 to see the cusp of this problem.

**Comment by gregturn** [comment]
Turns out that missing `like` is critical. When you have a query like this (with the `like` on the last clause):

```
		@Query("""
				select  c.username as username,
						c.mobile as mobile,
						tm.role as role,
						tm.clientId as clientId,
						c.name as clientName,
						c.email as email,
						tm.createTime as createTime
				                from TeamMember tm
				                left join SpringUser c
				                on tm.clientId = c.id
				                where tm.teamId = :teamId
				                and c.username like %:keywords%
				                or c.mobile like %:keywords%
				""")
		User textBlockQuery(String keywords);
```

...then it will work like this:

```
	@Test
	void textBlocksShouldParse() throws NoSuchMethodException {

		QueryLookupStrategy strategy = JpaQueryLookupStrategy.create(em, queryMethodFactory, Key.CREATE_IF_NOT_FOUND,
				EVALUATION_CONTEXT_PROVIDER, new BeanFactoryQueryRewriterProvider(beanFactory), EscapeCharacter.DEFAULT);

		Method method = UserRepository.class.getMethod("textBlockQuery", String.class);
		RepositoryMetadata metadata = new DefaultRepositoryMetadata(UserRepository.class);

		RepositoryQuery query = strategy.resolveQuery(method, metadata, projectionFactory, namedQueries);

		assertThat(query).isInstanceOf(SimpleJpaQuery.class);
		SimpleJpaQuery jpaQuery = (SimpleJpaQuery) query;
		String queryString = jpaQuery.getQuery().getQueryString();
		assertThat(queryString).isEqualTo("select  c.username as username,\n" +
				"\t\tc.mobile as mobile,\n" +
				"\t\ttm.role as role,\n" +
				"\t\ttm.clientId as clientId,\n" +
				"\t\tc.name as clientName,\n" +
				"\t\tc.email as email,\n" +
				"\t\ttm.createTime as createTime\n" +
				"                from TeamMember tm\n" +
				"                left join SpringUser c\n" +
				"                on tm.clientId = c.id\n" +
				"                where tm.teamId = :teamId\n" +
				"                and c.username like :keywords\n" +
				"                or c.mobile like :keywords\n");
	}
```
It's important to note that Spring Data JPA actually pulls out the `%` when it sees them and applies them to the bound variables, which is why you don't see them in the final string query in that test case.

However, when you leave out `like` in the last clause, as original reported, then things kind of fall apart and the final query looks like this:

```
select  c.username as username,
  		c.mobile as mobile,
  		tm.role as role,
  		tm.clientId as clientId,
  		c.name as clientName,
  		c.email as email,
  		tm.createTime as createTime
                  from TeamMember tm
                  left join SpringUser c
                  on tm.clientId = c.id
                  where tm.teamId = :teamId
                  and c.username like :keywords
                  or c.mobile %:keywords%
```
As you can see, due to the missing `like` in the last clause, Spring Data JPA can't properly strip out the percentage signs. And either way, the query is wrong.

But apart from that, all the extra spaces and tabs are nicely preserved, so in fact, Java 17 text blocks appear to work just fine.

**Comment by shuanshuan** [comment]
@gregturn I don't have the issue with like or % .

**Comment by gregturn** [comment]
Could you include a link to a reproducer, staged on github, ideally using https://start.spring.io, H2 (or Testcontainers for PostGreSQL, etc.), and the version of Spring Boot aligned with your issue? I crafted a test case using text blocks, as shown above, and it seemed to handle it just fine. So we need something that hones in the exact issue to trace where the problem is.

**Comment by kamikaze011001** [comment]
![image](https://github.com/spring-projects/spring-data-jpa/assets/106855369/459aba80-46bf-47b2-b534-a2ba08711608)
i can't use projection DTO with text block

**Comment by rishiraj88** [comment]
Quite interesting. I, too, like to learn its solution.

**Comment by schauder** [comment]
@kamikaze011001 This seems completely unrelated.

To everyone else:
We still need a reproducer.

If you want to make your interest in this issue visible, leave a thumbs up on the original post. 
"Me 2" comments just makes working on issues a pain.
