### ISSUE TITLE
Extending SimpleJpaRepository (fixing problems in JPA spec)

### ISSUE THREAD

**Issue by bjconlan** [spring-projects/spring-data-jpa#3]
I'm currently implementing a CascadeBulkDeleteJPARepostory to rectify a problem we are having with bulk deletes not removing @EmbeddedCollections. This is a well known problem (see http://stackoverflow.com/questions/3903202/how-to-do-bulk-delete-in-jpa-when-using-element-collections) and am overwriting the SimpleJPARepository to fix such a problem (temporarily just by performing deleteAll(Collection<T>) at this stage). But I would find it beneficial to have access to the variables set by the constructor (at least in 1.0.0.M2).

Now obviously I currently maintain a reference to the objects in my implementation but providing a:

EntityManger getEntityManager()
 and
JpaEntityInformation<T, ID> getEntityMetadata()

in the SimpleJPARepostory would be quite useful for such cases.

Thanks & great work.

**Comment by gregturn** [comment]
This appears to be a JPA-specific issue which is currently NOT SUPPORTED (read the updated comments on the linked SO response).

However, according to https://hibernate.atlassian.net/browse/HHH-5529, this has been has been added to [Hibernate 6](https://hibernate.atlassian.net/browse/HHH-14946?jql=project%20%3D%20%22HHH%22%20AND%20fixVersion%20%3D%20%226.0.0.Beta2%22). However, there are a multitude of issues that bar us from adopting HIbernate 6 at this point in time.

Please feel free to revisit whenever you are able to adopt Hibernate 6 and see if this issue is still a problem.
