### ISSUE TITLE
`QuerydslJpaPredicateExecutor` calls deprecated api(fetchCount)

### ISSUE THREAD

**Issue by le2sky** [spring-projects/spring-data-jpa#3007]
`fetchCount` has been deprecated since `queryDsl 5.0` however, `spring-data-jpa 3.1` still uses fetchCount.

`AbstractJPAQuery.java` : 
```java
   ...
    @Override
    @Deprecated
    public long fetchCount() {
        try {
            if (getMetadata().getGroupBy().size() > 1 || getMetadata().getHaving() != null) {
                logger.warning("Fetchable#fetchCount() was computed in memory! See the Javadoc for AbstractJPAQuery#fetchCount for more details.");
                Query query = createQuery(null, false);
                return query.getResultList().size();
            }

            Query query = createQuery(null, true);
            return (Long) query.getSingleResult();
        } finally {
            reset();
        }
    }
    ...
```
`QuerydslJpaPredicateExecutor.java` in spring-data-jpa/**/repository/support :
```java
   ...
    @Override
    public long count(Predicate predicate) {
        return createQuery(predicate).fetchCount();
    }
    ...
```

**Comment by gregturn** [comment]
Unfortunately, the solution isn't cut and dry. For starters, the deprecation notice from Querydsl doesn't give a simple API to migrate to. Instead, it spells out the design issues with issuing `select COUNT(*)` calls within the limits of JPA. It also describes how Querydsl deals with doing counts.

They also make reference to a technology with stronger ability to handle this sort of thing (Querydsl Integration with Blaze-Persistence) due to its inbuilt support for pagination. Spring Data JPA isn't about to introduce such a strong dependency like that.

This isn't exactly one API being replaced with another, but instead a more subtle issue. We'd need to consult whether its acceptable risk to go along with Querydsl's existing `fetchCount()` or switch to what would probably be self-written solution that wraps around JPA and Querydsl's other APIs.

If you more suggestions on where to go, we'd love to hear your inputs.

**Comment by mp911de** [comment]
The deprecation is in place to report a warning regarding query result size for queries using `GROUP BY` or `HAVING`. While `GROUP BY` isn't ideal for entities, `HAVING` can be used in those queries. Our own `PagedExecution` uses the same semantics to inspect whether the result is a single row or whether a `GROUP BY` query yields multiple count results.

**Comment by le2sky** [comment]
Thanks for answer 🙇‍♂️🙇‍♂️

**Comment by gregturn** [comment]
Seeing no immediate action, I'm closing this ticket.
