### ISSUE TITLE
Not able to hit native query with postgres

### ISSUE THREAD

**Issue by dilipdhankecha2530** [spring-projects/spring-data-jpa#3022]
Database contains the data but not able to get those data from database with entity manager native query.

```
this.entityManager.createNativeQuery("select T.id,T.attackDate, (select count(id) from fraud_case fc2 where fc2.type_id = T.id and fc2.attack_date=T.attackDate) from (SELECT ft.id , date_trunc('day', dd)\\:\\: date as attackDate FROM generate_series         ( '2023-06-01' \\:\\: timestamp, '2023-06-09' \\:\\: timestamp , '1 day' \\:\\: interval) dd cross join fraud_type ft where ft.id in (2)) as T").getResultList();
```

**Comment by dilipdhankecha2530** [comment]
Suggest a JPA query as well to achieve this functionality.

**Comment by schauder** [comment]
This sounds very much like a Hibernate issue, since all the JPA mapping is done by it.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` directly.
