### ISSUE TITLE
Hibernate ignores `spring.jpa.hibernate.ddl-auto:none` with Liquibase

### ISSUE THREAD

**Issue by ilkou** [spring-projects/spring-data-jpa#3023]
I encountered an issue where `Hibernate` is not respecting the `'spring.jpa.hibernate.ddl-auto:none'` configuration when `Liquibase` is used in a Spring Boot application. This problem started after upgrading to Spring Boot `3.0.0` (also `3.0.5`, `3.0.6` and `3.1.0` )

Before the upgrade, with `'spring.jpa.hibernate.ddl-auto:none'`, Hibernate correctly avoided altering the database schema. However, in the new version, Hibernate is making changes to the schema despite the explicit `'none'` setting. For instance, when adding an attribute to an '@Entity' class, Hibernate automatically adds the corresponding column to the database table.

To resolve this issue, I had to set `'spring.jpa.properties.hibernate.hbm2ddl.auto:none'`.
This workaround seems necessary even though `Liquibase` is supposed to handle all schema changes.

**Comment by gregturn** [comment]
For starters, `spring.jpa.hibernate.ddl-auto` is a Spring Boot property. It's mean to support multiple paradigms including Hibernate and JPA. If Spring Boot sees `hibernate.hbm2ddl.auto` populated, THAT is what it will ascribe to `ddl-auto` and feed back. If it instead sees `spring.jpa.hibernate.ddl-auto`, it will associate that with `ddl-auto`. If instead it sees `jakarta.persistence.schema-generation.database.action`, it will simply null out `ddl-auto`. 

Now if the value of `ddl-auto` is populated, but not with `none`, then it will apply that setting to `hibernate.hbm2ddl.auto`. Thus, if you had used that all along, it is pulled out and reapplied. However, if the value of `ddl-auto` is `none`, it will actually remove `hibernate.hbm2ddl.auto`` from the map of settings. That's because `hibernate.hbm2ddl.auto` has a default value of `none`.

This entire behavior I just described has actually been there for almost five years.

A key change that happened between Spring Boot 2.7 and 3.0 was an upgrade from Hibernate 5.x to 6.1, so my suspicion is that something there has changed with regards to Hibernate. My suggestion is to switch on log flags inside `application.properties` and try to glean a little more information on what Hibernate is up to.

```
logging.level.org.springframework.data.jpa=TRACE
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
```

Now if you're saying this ONLY happens when Liquibased is on the classpath, that sounds like something else entirely.

**Comment by ilkou** [comment]
After testing a clean new project with and without Liquibase, I can confirm that everything is working as expected.

I went back to the project where we encountered the issue and did some digging to find a `SPRING_JPA_HIBERNATE_DDL_AUTO=update` inside the `.env` file 👀
To be honest, I wasn't aware of this as I don't usually work on this project and was just helping out a collaborator who sought assistance.

I genuinely appreciate your time and effort in explaining these properties. thank you so much for your support and clarification :pray:
