### ISSUE TITLE
Spring Data should generate a LEFT JOIN instead of a JOIN if deciding to automatically join due to a sort expression in a pageable.

### ISSUE THREAD

**Issue by Bas83** [spring-projects/spring-data-jpa#3042]
If we have a simple

```
@Query("""
    SELECT b FROM Book b
    """)
Page<Book> find(Pageable pageable);
```

And Book has a reference to a book series, which is optional.

Consider this pageable contains a sort expression through that reference, `series.name` then the query will automatically do a JOIN on the series table.
However, this means that the results become constrained automatically on only books that have a series. I think the query should generate a LEFT JOIN instead. ESPECIALLY if the reference isn't annotated with `nullable = false` in the entity, although I would just always do it anyway.
[spring-data-bug.zip](https://github.com/spring-projects/spring-data-jpa/files/11889698/spring-data-bug.zip)

**Comment by gregturn** [comment]
I'm not (yet) convinced we need to do this sort of alteration to a query. You're suggesting that due to the `WHERE` clause bringing in an implicit JOIN, and it altering the nature of the query, we should further alter it by making it an OUTER join.

First of all, it's tricky to capture that this is what's happening. It also implies we'd need to spot in the most complex of queries, when we are explicitly joining and when we aren't.

For example, what if if were `@Query("SELECT b from Book b JOIN b.series")`? Would be respect the original query in that context? Or go ahead and blindly apply the LEFT qualifier? If someone has explicitly done a JOIN like that, how can we tell when we the LEFT is right vs. wrong? That is a semantic difference we may not be able to spot.

Frankly, I'd rather NOT alter such a query at all, since there is no originating JOIN yet applied. If somehow the WHERE clause is causing a JOIN that doesn't fit the semantics of this operation, and considering `@Query` is your mechanism to customize things, I'd suggest it's up to you to put in the correct JOIN operation so the filtering acts as expected.

**Comment by Bas83** [comment]
@gregturn it's not due to the WHERE clause but due to a sort expression in the Pageable object.

I can't talk about how it works internally so I don't know how hard it is to spot you added a JOIN because of some requirements.
But yes it should respect the original query, if some JOIN is already there then just leave it alone, but if adding it automatically then in my opinion it should go the least destructive path. A LEFT JOIN doesn't restrict the return values, but a default INNER JOIN can and that's pretty dangerous.

As for your last comment, yes I would prefer just not adding joins over adding result-restricting joins. Then at least the query would just break immediately and obviously. But that isn't the case right now, the JOIN is added but you won't know it doesn't restrict the results until you really have specific test cases where the reference being sorted on is optional and there are objects without them too.

How I found out btw, is because we did actually have a LEFT JOIN specified, but the alias for the table that was ordered on didn't match the sort attribute, and then Spring Data optimized that LEFT JOIN away and added the regular JOIN that restricted the data. It would have been more helpful if it just failed. I initially filed a ticket with Hibernate for this as I thought they generated all the queries. https://hibernate.atlassian.net/browse/HHH-16856

**Comment by gregturn** [comment]
Okay, reading that Hibernate ticket was illuminating. And yes...when you submit a ticket to the Hibernate team, they prefer it to be Spring-free.

All that being said, I finally unravelled the issue...and found a solution using your posted example to the Hibernate ticket you opened.

Because your query was this:

```java
@Query("""
    SELECT ak FROM ApiKey ak
    LEFT JOIN ak.role r
    """)
Page<ApiKey> custom(Pageable pageable);
```
...you have aliased LEFT JOIN relationship with `r`. However, your `Order` is created like this:

```
Order order = new Order(Direction.ASC, "role.name"); // <-- using "role", the name of the relationship in the mapping
```

Using the debugger, I could see the `LEFT JOIN` being turned over to Hibernate along with `order by role.name`, but Hibernate itself saw the `order by role.name` and with `role` unrelated to anything else, automatically applied a new JOIN. Since it was the same relationship as the LEFT JOIN you had created by hand, it replaced yours with its new JOIN (I believe).

If you alter your `Order` to this: 

```
Order order = new Order(Direction.ASC, "r.name"); // <--- use the alias "r" instead of the name
```
...then the submitted query is `SELECT ak FROM ApiKey ak LEFT JOIN ak.role r order by r.name asc`. Hibernate no longer sees a reason to ADD a new JOIN and instead accepts the original LEFT JOIN that you wrote, thus making the test case go green.

**Comment by gregturn** [comment]
Based on this, it looks like any/all changes from LEFT JOIN to JOIN were on Hibernate's side. We simply add an ORDER BY clause with the named property from the `Order` object, sometimes with aliasing sometimes not. We don't directly alter JOIN clauses (except for a very specific scenario involving FETCH JOIN operations), hence I've marked this ticket as `declined`.

Hope that clears things up on your end.

**Comment by subodhcjoshi82** [comment]
Same issue i am facing in my project
**spring-jpa-2.7.0**
```
select *  from 
  catuser23.ITEMS item0_ left outer join catuser23.LIFECYCLE_STATES lifecycles1_ on item0_.LIFECYCLE_STATE_ID=lifecycles1_.LIFECYCLE_STATE_ID 
 where lower(item0_.VALID)=? and 
 (item0_.TYPE=? and lower(lifecycles1_.ALLOW_INSTANCES)=? or item0_.TYPE=? and
 (item0_.CHECKOUT_USERNAME is null or item0_.CHECKOUT_USERNAME=?) or item0_.TYPE=?) order by item0_.NAME asc
```
 
 **spring-jpa-3.2.2**
```
 select * from  
 catuser23.ITEMS i1_0 join catuser23.LIFECYCLE_STATES ls2_0 on ls2_0.LIFECYCLE_STATE_ID=i1_0.LIFECYCLE_STATE_ID
 where lower(i1_0.VALID)=? and 
 (i1_0.TYPE=? and lower(ls2_0.ALLOW_INSTANCES)=? or i1_0.TYPE=? and 
 (i1_0.CHECKOUT_USERNAME is null or i1_0.CHECKOUT_USERNAME=?) or i1_0.TYPE=?) order by i1_0.NAME
 
 
```
So Hibernate /Spring Data replacing **LEFT OUTER JOIN** from the I**NNER JOIN**. 
 
 In my case i am using Specification to create the query something like this
 	```
List<Item> items = new ArrayList<>();
		if (specs.size() > 0) {
			Specification<Item> result = specs.get(0);
			for (int i = 1; i < specs.size(); i++) {
				result = Specification.where(result).and(specs.get(i));

			}
			items = itemRepository.findAll(result, Sort.by(Direction.ASC, "name"));
```
 and as replied in comment section **Order By** is not a issue in my case, as query generated with `order by item0_.NAME asc`
