### ISSUE TITLE
IN clause related to multiple columns

### ISSUE THREAD

**Issue by sahraoui62** [spring-projects/spring-data-jpa#3100]
Hello.

I have one suggestion about a problem that I encountered.

In this example, I want to find all users with a specific name and year : 
David 50 years old, Sylvie 44 years old and Camille 23 years old. 

I find only one way to do it, is by creating a custom query and by concatenating the two fields into one String to be able to filter on these two columns at the same time.

```
@Repository
interface UserRepository : JpaRepository<User, Int> {

    @Query(
            nativeQuery = true,
            value = "SELECT * FROM user u where concat(u.name, '-', u.year) in (:nameAndYear)"
    )
    fun findByNameAndYear(nameAndYear: List<String>) : List<User>

}
```

Unit test example :

```
 @Test
    fun `Method findByNameAndYear should only return corresponding users`() {
        val user1 = User(name = "David", year = 50)
        val user2 = User(name = "Sylvie", year = 44)
        val user3 = User(name = "Camille", year = 10)

        repository.save(user1)
        repository.save(user2)
        repository.save(user3)

        assertThat(repository.findByNameAndYear(listOf("David-50", "Sylvie-44", "Camille-23")))
                .containsExactlyInAnyOrder(user1, user2)
    }
```

I would like to know if it is possible to have new keywords like for example: 
`fun findByPairNameAndYear(pairs : Pair<String, Int>) : List<User>` in kotlin

**Comment by gregturn** [comment]
I'm not aware of how to write a native query that does what you're asking without doing the concatenation thing you speak of. Maybe there is some way to write a correlated subquery, but frankly I can't see it. Which is probably why you can't leverage a `Pair` type the way you're thinking.

Perhaps you'd get more mileage if you posted your question on StackOverflow and labeled it JPA and Hibernat?

**Comment by mp911de** [comment]
FWIW, Spring JDBC supports the expansion of `List<Object[]>` into tuples for tuple in-query usage, such as `select * from demo where (fn, ln) in (('a', 'a-a'))` (`create table demo (fn varchar(255), ln varchar(255));`). However, since queries are ran by JPA, I'm not sure such a feature is supported there as well.

**Comment by gregturn** [comment]
Based on lack of tuple-based query support in JPA, I'm closing this ticket.

**Comment by maxisbrocca** [comment]
Hi. I understand this ticket is closed. I understand the conversation initialization concern. I have a similar issue, but instead of sharing my java code, I'll share what's the final query I want to get to see is is possible to achieve that or if it can be proposed as a future feature.

As @sahraoui62, I need to get entities querying if several of this entity fields at the same time has defined value. In other words, I need to search by tuples. The final SQL query I need to get is:

`select * from member m where (m.program, m.country) IN (('PROGRAM1', 'US'), ('PROGRAM2', 'UK'), ('PROGRAM3', 'AR'))`

This is a valid SQL query, but seems is not possible to get using Spring Data JPA.

I hope this clarify the requirement. If this is supported today, please let me know how to perform it.

Thanks!
