### ISSUE TITLE
Spring boot 3.1.2 use JpaRepository saveAndFlush return entity not synchronized with Database

### ISSUE THREAD

**Issue by lebkset** [spring-projects/spring-data-jpa#3115]
I have entity :

```
@Entity
Student {
  @Id
    @Column(name = "student_id", nullable = false)
    @GeneratedValue(strategy = GenerationType.UUID)
    String studentId;
}
```

I create sql trigger in db migration generate studentId before insert:

```
CREATE or REPLACE FUNCTION student_id_generate() RETURNS TRIGGER AS
$BODY$
DECLARE
    next_student_id TEXT;
BEGIN
    SELECT INTO next_student_id 'abcd'
    FROM student

    NEW.next_student_id = next_student_id;
    RETURN NEW;
END;
$BODY$
    LANGUAGE plpgsql;

CREATE TRIGGER generate_student_id_trigger
    BEFORE INSERT
    ON student
    FOR EACH ROW
EXECUTE PROCEDURE student_id_generate();

```

**When I call repository.saveAndFlush return entitySaved then entitySaved.studentId is value of @GeneratedValue(strategy = GenerationType.UUID)** but in database then studentId is value generate from sql trigger

**Note** : when I use spring boot 2.7.5 then studentId is value generate from sql trigger

**Comment by schauder** [comment]
The behaviour you describe is exactly what I would expect, from how JPA works. The only thing that surprises me is that you say it worked differently in earlier versions.

Anyway, this change in behaviour sounds very much like a Hibernate issue, since id generation is handled by JPA and that is implemented by Hibernate.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` directly.

**Comment by lebkset** [comment]
Thank for your comment , I will consider about Hibernate
