### ISSUE TITLE
with tow type database, mysql in local and postgres in production, what can i do set tow nativeQuery sql  by @Query annotation 

### ISSUE THREAD

**Issue by loujiaye** [spring-projects/spring-data-jpa#3214]
@Query(value = "select date_format(t.created_date , '%Y-%m-%d') as date, count(t.id) as num, count(r.id) as doTodoNum from todo t left join record r on t.id = r.todo_id  where t.user_id = ?1 and unix_timestamp(t.created_date) between ?2 and ?3 group by date_format(t.created_date , '%Y-%m-%d') order by date", nativeQuery=true)
    List<TodoStaticDto> staticsByUserAndCreatetime( long user_id, long start, long end);

in local, mysql database.  it`s work.

but in production environment, i use postgre.  it`s not work

![image](https://github.com/spring-projects/spring-data-jpa/assets/9496863/9632bc7b-82ed-415d-97de-576b6e0c08a7)

I want set different sql in different environment,how can i do?

**Comment by gregturn** [comment]
I don't believe we currently have support for injecting queries into @Query using SpEL or delegating to some injected property setting. Frankly I'm skeptical of doing such a thing because injecting queries like that would open a potential vector of attack we may not want to go down that road.

I'm wondering if there were a way to create a base repository definition, flag is at `@NoRepository`, and then extend it with a `MySqlTodoRepository` that has your MySQL query and a `PostGresToDoRepository`.

This would give you two repositories which you could then perhaps conditionally ignore using some Spring Boot `@Conditional` settings based upon which repository is online.

**Comment by loujiaye** [comment]
thanks for answer. it could solve my problem.

I use navtiveQuery because of i want to do soft deleted  by HIbernate @Where annoatition and statistics deleted 'todo', but i find way to do it without nativeQuery in jpa

<img width="1155" alt="截屏2023-10-29 下午9 22 43的副本" src="https://github.com/spring-projects/spring-data-jpa/assets/9496863/87f9d8b9-a7a0-46c4-b4ad-18613cb56f9f">



About nativeQuery, i think it should bind with DataSource . so, if modifiy  it in futuer,  something like @Conditional  set by nativeQuery can help it
