### ISSUE TITLE
Enum Constraint Not Updated in Spring Data JPA

### ISSUE THREAD

**Issue by hemantmaersk** [spring-projects/spring-data-jpa#3299]
**Issue Description:**

### Problem Statement
When using Enums in a Spring Data JPA entity, it appears that the database constraint is added correctly during the initial creation of the table. However, when the Enum is later updated with new values, the corresponding database constraint is not automatically updated, leading to inconsistencies between the Enum definition and the database schema.

### Expected Behavior
The database constraint for the Enum column should be automatically updated whenever there is a change in the Enum values.

### Actual Behavior
The database constraint is not updated when Enum values are modified.

### Steps to Reproduce
1. Create a JPA entity with an Enum field.
2. Let the entity be persisted, creating the corresponding database table and constraint.
3. Update the Enum in the Java code.
4. Observe that the database constraint is not updated to reflect the changes in the Enum.

### Sample Code

```java
@Entity
public class SampleEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(name = "sample_enum", nullable = false)
    private SampleEnum sampleEnum;

    // other fields and methods
}

public enum SampleEnum {
    VALUE1,
    VALUE2,
    // ... add or remove Enum values
}
```

### Additional Information
- Spring Boot Version: 3.2.1
- Database: PostgreSQL

This issue is raised to discuss and address the mentioned problem. Any insights or solutions would be greatly appreciated. Also please let me know if I need to raise issue in external project, I will be happy to do that.

**Comment by quaff** [comment]
It's nothing related to Spring Data JPA, It belongs to Hibernate, and it's not specific to enum constraint.
Hibernate only detects column's existence, it doesn't detect column's definition changes, For example if you change `boolean enabled` to `Boolean enabled`, the column will not remove `not null` constraint. 
I think it's reasonable to limit that because it may corrupt existing data, you should alter it manually, and use data migration tool like `Flyway` and `Liquibase` for production, Don't rely on hibernate's schema generation, unless initial version.

**Comment by ea241832** [comment]
How can we then disable it?
