### ISSUE TITLE
I'm curious about the difference between the "deleteIn~" method and the "deleteIn~Batch" method.

### ISSUE THREAD

**Issue by sami355-24** [spring-projects/spring-data-jpa#3318]
As far as I know, the difference between the two methods is that DB has or does not have the "In" keyword in its deletion query. However, when the "Batch" keyword was attached, it was confirmed that the function provided by the persistence context was not used.

Is there a particular reason why data jpa works this way? If not, I think it would be better in terms of performance for the Batch keyword to go through the persistence context as well.

Furthermore, if there is no specific reason, I would like to try a country interview with that content.

**Comment by christophstrobl** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
