### ISSUE TITLE
CASCADING DELETE not working as expected in derived query

### ISSUE THREAD

**Issue by 4braincells** [spring-projects/spring-data-jpa#3535]
```
@Repository
public interface LessonInstanceRepo extends Repo<LessonInstance> {
    // jpa approach
    @Modifying
    @Query("delete from LessonInstance t where t.baseIdentity.schoolId = :schoolId")
    int deleteBySchoolId(@Param("schoolId") Integer schoolId);

    // derived query approach
    long deleteByBaseIdentitySchoolId(@Param("schoolId") Integer schoolId);
}
```

Both queries seem to recognize the 1:n relationship declared by@OneToMany and @JoinColumns.
Pls refer to [my question in the Hibernate forum](https://discourse.hibernate.org/t/please-explain-the-difference-cascading-delete-not-working-as-expected/9868/1) for more details.

The difference is that the `@Modifying @Query `obviously does (correctly) a DELETE CASCADE, while the **derived query** performs a DELETE SET NULL (speaking in DB language), thus ignoring the updatable=false attribute, causing a crash on database level (constraint violation , key must not be NULL).

(apologies for asking here, I can't access stackoverflow, login does not work with any of my accounts)

**Comment by schauder** [comment]
Sorry to here that you cannot log to Stackoverflow. Nevertheless, this is a prototypical question for Stackoverflow.

I'm not sure what exactly is going on here, but I have no indication that it is a Spring Data problem. 
I'd assume that it is a mixture of a broken mapping and the difference JPA makes between criteria API and JPQL.

The mapping is broken, because it seems you want to have a bidirectional mapping between your two entities, but you do have two independent references which get mapped to the same database field. This is not a good situation and it is basically undefined what is going to happen.

Queries given in `@Query` annotations are basically passed on to the `EntityManager` as is.
For derived queries we create a Criteria API query.
The handling of references is left to the JPA implementation and a quick search on the specification didn't turn anything up for me, so I can't really help there.

In order to make progress I recommend the following:

1. fix your mapping. Stackoverflow should be of great help here.
2. If the problem persist, execute the query using the `EntityManager` directly once, with a criteria query and once with a JPQL query. I'm confident that you'll see the same difference and with that the Hibernate people should be able to help. If you don't see the problem with those, then you can use this code as a reproducer and create a new issue here.

Good luck
