### ISSUE TITLE
Add ability to filter by the modified flags in the Envers repository

### ISSUE THREAD

**Issue by TMRGZ** [spring-projects/spring-data-jpa#3625]
See https://github.com/spring-projects/spring-data-jpa/pull/3626

**Comment by schauder** [comment]
Please don't create PRs with substantial changes for new features without a proper issue, that actually does discusses the changes. An issue simply referencing the PR does not qualify.

In principle being able to query for modified fields is a potentially interesting feature and as demonstrated by the PR not to difficult to actually implement as [Hibernate Envers allows to gather the information with some simple configuration](https://docs.jboss.org/hibernate/core/4.1/devguide/en-US/html/ch15.html#envers-tracking-properties-changes).

But the PR at hand only solves when very specific query scenario: Find revision where all fields from a provided set are modified. And it hard codes this query in the API, which is an approach which is not scalable.

I could envision a solution where this is implemented as query derivation, with a custom predicate isChanged for single properties and a virtual property ChangedFields and predicate containsAll and containsAny

But stepping away from the technical solution, the question remains: should we implement it? Since this is the first time I encounter this requirement and it requires a considerable amount of custom logic (I don't think we have virtual columns anywhere yet) I'm voting against it.
