### ISSUE TITLE
Weird behavior after retrieving select

### ISSUE THREAD

**Issue by Red44** [spring-projects/spring-data-jpa#3629]
When logging with p6spy [basically a JDBC man in the middle attack], it becomes apparent, that every select done by springboot jpa/hibernate is followed by a bunch of validation statements resulting in an N+1 problem, that hasn't been noticed, because the normal hibernate logging framework seems to hide them.
p6spy shows that each of these checks take something between 0.2 and 0.5ms depending on your resultset, performance issues arise.

[Proof](https://github.com/Red44/jpa-check-validation)

**Comment by quaff** [comment]
Because you are using `assigned` ID generator and not implementing `isNew()`, Spring Data JPA assume it's not new using `entityManager.merge()` instead of `entityManager.persist()`, `merge` will issue a `select` first to decide `insert` or `update`.

https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/SimpleJpaRepository.java#L618-L628

**Comment by mp911de** [comment]
First of all, there is only a single `SELECT` statement being logged, the remaining statements show result rows.

Second issue is that Hibernate has to run a `SELECT`, how else is it supposed to fetch data?

All this is expected and since Spring Data JPA isn't running any SQL on its own, rather it uses an underlying JPA provider, all subsequent statements are subject to your JPA provider.
