### ISSUE TITLE
@Id GenerationType.IDENTITY fails when setting id manually

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-data-jpa#3720]
spring-boot-starter-parent-3.3.5: OK
spring-boot-starter-parent-3.4.0: FAILURE

Since boot 3.4.0, the following test fails.
Has there been a change on purpose, so that the prior behavior was actually false, and has now been corrected?
Or is this a bug?

I noticed: downgrading `hibernate also fixed the issue: ` <hibernate.version>6.5.3.Final</hibernate.version>` (= version from boot 3.3.5)

```java
@Entity
public class Person {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;

    public String lastname;

    protected Person() {
        //hibernate
    }
}

@SpringBootTest
class DemoApplicationTest {
	@Autowired
	private PersonRepository dao;

	@Test
	public void testPersist() {
		Person b = new Person();
		b.id = 1L;
		b.lastname = "Doe";

		dao.save(b);
		assertEquals(1, dao.count());
	}
}
```

[demo.zip](https://github.com/user-attachments/files/18166952/demo.zip)

Sidenote: I cannot remember exactly why I was setting the ID here manually. Probably there was an issue with the generated sequence ids at time of writing.

**Comment by schauder** [comment]
This sounds very much like a Hibernate issue, since all the JPA mapping is done by it, including the id generation.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` directly.
