### ISSUE TITLE
Add support for soft deletes [DATAJPA-307]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#676]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATAJPA-307](https://jira.spring.io/browse/DATAJPA-307?redirect=false)** and commented

---

**Issue Links:**
- [DATAJPA-1551](https://jira.spring.io/browse/DATAJPA-1551) Create an API to customize query creation and query processing

- [DATAMONGO-1151](https://jira.spring.io/browse/DATAMONGO-1151) Introduce ability to append queries against a particular collection

- [DATACMNS-293](https://jira.spring.io/browse/DATACMNS-293) Add infrastructure for generic query augmentation

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/48

74 votes, 64 watchers

**Comment by lin-mt** [comment]
It's been almost eight years. When will the feature be officially released.

**Comment by schauder** [comment]
Once one starts to look into this in detail it becomes really complex.

You can implement this using native Hibernate features though. Search for "Hibernate soft deletes" in your preferred search engine.

See for reference: https://github.com/spring-projects/spring-data-commons/issues/766#issuecomment-752397179

We might also consider building an example how this could be achieved in order to explore the limitations. See #2163

**Comment by gregturn** [comment]
Having also looked at this, I don't think framework should handle it. It's best handled out of band.
